phrase:
  project_id: b27f8d323a573d8f17d5a22861b77242
  push:
    sources:
      - file: ./content/src/fieldConfig/tax-clearance-certificate-step1.json
        params:
          file_format: react_nested_json
          locale_id: en-US
          autotranslate: false
  pull:
    targets:
      - file: ./content/src/fieldConfig/tax-clearance-certificate-step1<locale_code>.json
        params:
          file_format: react_nested_json
          locale_id: en-US
