nodeLinker: node-modules

logFilters:
  - code: YN0032
    level: discard
  - code: YN0060
    text: "@storybook/nextjs"
    level: discard
  - code: YN0060
    text: "decap-cms"
    level: discard
  - code: YN0060
    text: "slate-base64-serializer"
    level: discard
  - code: YN0060
    text: "slate-plain-serializer"
    level: discard
  - code: YN0060
    text: "remark-slate-transformer"
    level: discard
  - code: YN0068
    level: discard
  - code: YN0069
    level: discard

packageExtensions:
  "@storybook/blocks@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/theming@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/nextjs@*":
    peerDependenciesMeta:
      next:
        optional: true
  "@storybook/addon-designs@*":
    peerDependenciesMeta:
      "@storybook/manager-api":
        optional: true
      "@storybook/preview-api":
        optional: true
  "@storybook/addon-controls@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/manager-api@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "slick-carousel@*":
    peerDependenciesMeta:
      jquery:
        optional: true
  "focus-trap-react@*":
    peerDependenciesMeta:
      prop-types:
        optional: true
  "@aws-sdk/credential-provider-web-identity@*":
    peerDependenciesMeta:
      "@aws-sdk/client-sts":
        optional: true
  "@aws-sdk/credential-provider-ini@*":
    peerDependenciesMeta:
      "@aws-sdk/client-sts":
        optional: true
  "@aws-sdk/token-providers@*":
    peerDependenciesMeta:
      "@aws-sdk/client-sso-oidc":
        optional: true
  "@react-email/render@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@react-email/preview-server@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "apollo-link@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  "apollo-cache-inmemory@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  "apollo-client@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  "apollo-link-http@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  "decap-cms-backend-git-gateway@*":
    peerDependenciesMeta:
      decap-cms-ui-auth:
        optional: true
  "decap-cms-app@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "react-transition-group@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "react-select@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "@dnd-kit/core@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "react-window@*":
    peerDependenciesMeta:
      react-dom:
        optional: true
  "eslint-plugin-storybook@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@testing-library/user-event@*":
    peerDependenciesMeta:
      "@testing-library/dom":
        optional: true
  "react-redux@*":
    peerDependenciesMeta:
      redux:
        optional: true
  "ts-node@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true
  "slate-base64-serializer@*":
    peerDependenciesMeta:
      slate:
        optional: true
  "slate-plain-serializer@*":
    peerDependenciesMeta:
      slate:
        optional: true
  "remark-slate-transformer@*":
    peerDependenciesMeta:
      unified:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.7.cjs
