name: "Docker Setup Navigator Builder Image"
description:
  "Installs AWS CLI, sets up Docker, checks out repo, and builds/pushes custom navigator builder
  image."

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI
      uses: ./.github/actions/install-awscli
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Build and Push Custom Node Image
      uses: ./.github/actions/build-and-push-custom-node-image
      with:
        image-name: bfs_navigator_builder-22_20_0
