services:
  static-site:
    build:
      context: ../..
      dockerfile: packages/static-site/Dockerfile.dev
    container_name: static-site
    image: businessnjgovnavigator-static-site:dev
    command: pnpm dev --hostname 0.0.0.0 --port 3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    networks:
      - static_site_network
    tmpfs:
      - /tmp
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./domain:/app/domain
      - ./messages:/app/messages
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./next.config.ts:/app/next.config.ts
      - ./proxy.ts:/app/proxy.ts
      - ./proxyAuth.ts:/app/proxyAuth.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ../../content:/content
      - static_site_next:/app/.next

networks:
  static_site_network:
    name: static-site-network

volumes:
  static_site_next:
    name: static-site-next
