export const LicenseScreenDefaults: Record<string, string> = {
  primaryCTAFirstLineText: "Apply for My License",
  primaryCTASecondLineText: "with the Division of Consumer Affairs",
  secondaryCTAFirstLineText: "I Submitted My Application",
  secondaryCTASecondLineText: "Check My Application Status",
  tab1Text: "Start Application",
  tab2Text: "Check Status",
  checkStatusText:
    "After you’ve applied for your license, input the information from your application below to get automatic updates about your application here in your roadmap.",
  businessNameLabel: "Business Name",
  businessNamePlaceholder: "Type your business name",
  address1Label: "Business Address Line 1",
  address1Placeholder: "Type your address",
  address2Label: "Business Address Line 2 (Optional)",
  address2Placeholder: "Type your address",
  zipCodeLabel: "Zip code",
  zipCodePlaceholder: "Type your zip code",
  stateLabel: "State",
  submitText: "Submit",
  errorText: "We cannot find your application.",
  fieldsRequiredText: "Please fill in all non-optional fields",
  foundText: "Great, we’ve found your application! Please check the details below.",
  permitStatusText: "Permit Status:",
  editButtonText: "Edit",
  pendingPermitStatusText: "Pending",
  activePermitStatusText: "Active",
  tooltipText:
    'Your license application status will update automatically after the Division of Consumer Affairs has received your application and you enter your identifying information into the "Check Status" tab below.',
};
