/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FirstName = string;
export type LastName = string;
export type Email = string;
export type WhatTypeOfCompanyDoYouWantToStart = "restaurant" | "other";
export type BusinessName = string;
export type BusinessDescription = string;
export type BusinessStructure = "LLC" | "LP" | "S-Corp";
export type NoName1 = [
  {
    title?: ZipCode;
    license?: AreYouInterstedInGettingALiquorLicenseForThisLocation;
    [k: string]: unknown;
  },
  ...{
    title?: ZipCode;
    license?: AreYouInterstedInGettingALiquorLicenseForThisLocation;
    [k: string]: unknown;
  }[]
];
export type ZipCode = string;
export type AreYouInterstedInGettingALiquorLicenseForThisLocation = boolean;

export interface NoName {
  user?: CreateANewAccount;
  businessType?: Welcome;
  /**
   * What do you want the Customer-facing name of your company to be? If you don’t know yet. Type ‘unsure’.
   */
  businessName?: {
    businessName?: BusinessName;
    [k: string]: unknown;
  };
  /**
   * In 1-2 sentences, describe the purpose of your business. This should be a brief statement about what you are setting out to accomplish, sell or produce.
   */
  businessDescription?: {
    businessDescription?: BusinessDescription;
    [k: string]: unknown;
  };
  businessStructure?: WhatTypeOfLegalStructureDoYouWantToCreateForYourBusiness;
  locations?: Locations;
  [k: string]: unknown;
}
export interface CreateANewAccount {
  firstName?: FirstName;
  lastName?: LastName;
  email?: Email;
  [k: string]: unknown;
}
/**
 * First we’ll need to ask you a few questions about your prospective business.
 */
export interface Welcome {
  businessType?: WhatTypeOfCompanyDoYouWantToStart;
  [k: string]: unknown;
}
/**
 * If you have not yet researched and determined the proper legal structure for your company, it is recommended that you consult a trusted advisor such as a lawyer or your local Small Business Development Center [link], before committing to a legal structure. You can click ‘unsure’ for now.
 */
export interface WhatTypeOfLegalStructureDoYouWantToCreateForYourBusiness {
  businessStructure?: BusinessStructure;
  [k: string]: unknown;
}
/**
 * Please indicate the desired Zip Code of each location, and whether or not you are interested in obtaining a liquor license. If you do not know the Zip Code yet. Type N/A.
 */
export interface Locations {
  locations?: NoName1;
  [k: string]: unknown;
}
