name: "Install Firefox"
description: "Installs Firefox when browser input equals 'firefox'."

inputs:
  browser:
    description: "Browser to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Firefox
      shell: bash
      run: |
        if [[ "${{ inputs.browser }}" == "firefox" ]]; then
          sudo apt update
          sudo apt install -y firefox
        fi
