version: 2.1

commands:
  bootstrap-code:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-yarn-deploy-deps-{{ checksum "yarn.lock" }}
            - v5-yarn-deps-{{ checksum "yarn.lock" }}
            - v5-yarn-deploy-deps-
            - v5-yarn-deps-
      - run:
          name: Install yarn packages
          command: yarn install

  setup-npm-global:
    steps:
      - run:
          name: Setup global npm storage
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH

  configure:
    steps:
      - run:
          name: Install Tools
          command: |
            sudo apt update
            sudo apt install -y openjdk-11-jdk-headless
      - bootstrap-code
      - run:
          name: Configure Amplify
          command: |
            export PATH=~/.npm-global/bin:$PATH
            ./scripts/amplify-ci/configure.sh
      - run:
          name: Configure Serverless
          command: yarn workspace @businessnjgovnavigator/api serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}

  configure-smoke-test:
    steps:
      - run: sudo apt update
      - setup-npm-global
      - bootstrap-code

  configure-and-build:
    steps:
      - setup-npm-global
      - configure
      - run:
          name: Build
          command: yarn build

  code-quality:
    steps:
      - run:
          name: Run Typecheck
          command: yarn typecheck
      - run:
          name: Run Cypress Typecheck
          command: yarn workspace @businessnjgovnavigator/web typecheck:cypress
      - run:
          name: Run Prettier
          command: yarn prettier
      - run:
          name: Run Linting
          command: yarn lint
      - run:
          name: Run Spell Checker
          command: yarn run spellcheck
      - run:
          name: Run Fences
          command: yarn fences
      - run:
          name: Run Unit Tests
          command: yarn test:ci

  perform-integration-tests:
    parameters:
      enable-dashboard:
        type: boolean
      suite:
        type: string
    steps:
      - run:
          name: Install Additional Tools
          command: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Start services
          command: yarn workspace @businessnjgovnavigator/api start & yarn workspace @businessnjgovnavigator/api start:wiremock & yarn workspace @businessnjgovnavigator/web start
          background: true
      - run:
          name: Run Tests
          command: yarn cypress:run --browser=chrome --record=<< parameters.enable-dashboard >> --env SUITE=<< parameters.suite >>
          working_directory: web
      - store_test_results:
          path: web/cypress/results
      - store_artifacts:
          name: Store Cypress Screenshots
          path: web/cypress/screenshots
      - store_artifacts:
          name: Store Cypress Videos
          path: web/cypress/videos

  perform-smoke-tests:
    parameters:
      enable-dashboard:
        type: boolean
      suite:
        type: string
    steps:
      - run:
          name: Install Additional Tools
          command: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Run Tests
          command: yarn cypress:run --browser=chrome --record=<< parameters.enable-dashboard >> --env SUITE=<< parameters.suite >> --config baseUrl=${SMOKE_TEST_ENV}
          working_directory: web
      - store_test_results:
          path: web/cypress/results
      - store_artifacts:
          name: Store Cypress Screenshots
          path: web/cypress/screenshots
      - store_artifacts:
          name: Store Cypress Videos
          path: web/cypress/videos

  store-cache:
    steps:
      - save_cache:
          key: v5-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/cache
            - ~/.npm-global
            - ~/.cache/Cypress

  store-deploy-cache:
    steps:
      - save_cache:
          key: v5-yarn-deploy-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/cache
            - ./web/.next/cache
            - ~/.npm-global
            - ~/.cache/Cypress

  deploy-serverless:
    steps:
      - run:
          name: Deploy Serverless
          command: yarn workspace @businessnjgovnavigator/api serverless deploy --verbose --stage ${STAGE} --region us-east-1

  deploy-amplify:
    steps:
      - run:
          name: Deploy Amplify
          command: |
            export PATH=~/.npm-global/bin:$PATH
            ./scripts/amplify-ci/publish.sh

  set-dev-env-vars:
    steps:
      - run:
          name: Set Development Environment Variables
          command: |
            echo 'export API_BASE_URL=$API_BASE_URL_AWS_DEV' >> $BASH_ENV
            echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_DEV' >> $BASH_ENV
            echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_DEV' >> $BASH_ENV
            echo 'export COGNITO_WEB_CLIENT_ID=$COGNITO_WEB_CLIENT_ID_DEV' >> $BASH_ENV
            echo 'export LICENSE_STATUS_BASE_URL=$LICENSE_STATUS_BASE_URL_DEV' >> $BASH_ENV
            echo 'export MYNJ_ROLE_NAME=$MYNJ_ROLE_NAME_DEV' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_TOKEN=$MYNJ_SERVICE_TOKEN_DEV' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_DEV' >> $BASH_ENV
            echo 'export REDIRECT_URL=$REDIRECT_URL_DEV' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV' >> $BASH_ENV
            echo 'export SMOKE_TEST_ENV=$SMOKE_TEST_ENV_DEV' >> $BASH_ENV

  set-cypress-env-vars:
    steps:
      - run:
          name: Set Cypress Environment Variables
          command: |
            echo 'export API_BASE_URL=http://localhost:5000/local' >> $BASH_ENV
            echo 'export REDIRECT_URL=http://localhost:3000/' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV' >> $BASH_ENV

  set-staging-env-vars:
    steps:
      - run:
          name: Set Staging Environment Variables
          command: |
            echo 'export API_BASE_URL=$API_BASE_URL_AWS_STAGING' >> $BASH_ENV
            echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_STAGING' >> $BASH_ENV
            echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_STAGING' >> $BASH_ENV
            echo 'export COGNITO_WEB_CLIENT_ID=$COGNITO_WEB_CLIENT_ID_STAGING' >> $BASH_ENV
            echo 'export LICENSE_STATUS_BASE_URL=$LICENSE_STATUS_BASE_URL_STAGING' >> $BASH_ENV
            echo 'export MYNJ_ROLE_NAME=$MYNJ_ROLE_NAME_STAGING' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_TOKEN=$MYNJ_SERVICE_TOKEN_STAGING' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_STAGING' >> $BASH_ENV
            echo 'export REDIRECT_URL=$REDIRECT_URL_STAGING' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STAGING' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STAGING' >> $BASH_ENV

  set-prod-env-vars:
    steps:
      - run:
          name: Set Production Environment Variables
          command: |
            echo 'export API_BASE_URL=$API_BASE_URL_AWS_PROD' >> $BASH_ENV
            echo 'export AUTH_DOMAIN=$COGNITO_AUTH_DOMAIN_PROD' >> $BASH_ENV
            echo 'export BUSINESS_NAME_BASE_URL=$BUSINESS_NAME_BASE_URL_PROD' >> $BASH_ENV
            echo 'export COGNITO_WEB_CLIENT_ID=$COGNITO_WEB_CLIENT_ID_PROD' >> $BASH_ENV
            echo 'export LICENSE_STATUS_BASE_URL=$LICENSE_STATUS_BASE_URL_PROD' >> $BASH_ENV
            echo 'export MYNJ_ROLE_NAME=$MYNJ_ROLE_NAME_PROD' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_TOKEN=$MYNJ_SERVICE_TOKEN_PROD' >> $BASH_ENV
            echo 'export MYNJ_SERVICE_URL=$MYNJ_SERVICE_URL_PROD' >> $BASH_ENV
            echo 'export REDIRECT_URL=$REDIRECT_URL_PROD' >> $BASH_ENV
            echo 'export FEATURE_DISABLE_OPERATE=$FEATURE_DISABLE_OPERATE_PROD' >> $BASH_ENV
            echo 'export FEATURE_DISABLE_OSCAR_ONBOARDING=$FEATURE_DISABLE_OSCAR_ONBOARDING_PROD' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD' >> $BASH_ENV

  deploy:
    steps:
      - configure-and-build
      - deploy-serverless
      - deploy-amplify

  deploy-storybook:
    steps:
      - install-awscli
      - run:
          name: Deploy Storybook
          command: yarn workspace @businessnjgovnavigator/web deploy:storybook --bucket-path $STORYBOOK_S3_BUCKET  --aws-profile=NONE

  install-chrome:
    steps:
      - run:
          name: Install Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb

  install-awscli:
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install awscli

  generate-release-notes:
    steps:
      - run:
          name: Install Github CLI
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt -y install gh
      - run:
          name: Generate Release Notes
          command: yarn semantic-release --branches $CIRCLE_BRANCH
      - run:
          name: Create PR to main
          command: |
            git status
            gh pr create --fill --base main --head $CIRCLE_BRANCH

jobs:
  build:
    docker:
      - image: cimg/node:14.18.2
    resource_class: large
    steps:
      - set-dev-env-vars
      - configure-and-build
      - store-cache
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  lint:
    docker:
      - image: cimg/node:14.18.2
    resource_class: large
    steps:
      - set-dev-env-vars
      - attach_workspace:
            at: .
      - configure
      - bootstrap-code
      - code-quality
      - store_test_results:
          path: coverage/test_results
      - store_artifacts:
          name: Store Jest Coverage
          path: coverage

  prepare-release:
    docker:
      - image: cimg/node:14.18.2
    resource_class: small
    steps:
      - set-prod-env-vars
      - setup-npm-global
      - bootstrap-code
      - generate-release-notes

  deploy-dev:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - set-dev-env-vars
      - attach_workspace:
            at: .
      - deploy
      - deploy-storybook
      - store-deploy-cache
    environment:
      STAGE: dev
      AMPLIFY_ENV: dev
      MYNJ_PROFILE_LINK: https://myt1.state.nj.us/portal/Desktop

  deploy-staging:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - set-staging-env-vars
      - deploy
    environment:
      STAGE: staging
      AMPLIFY_ENV: staging
      MYNJ_PROFILE_LINK: https://myt1.state.nj.us/portal/Desktop

  deploy-production:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - set-prod-env-vars
      - deploy
    environment:
      STAGE: prod
      AMPLIFY_ENV: prod
      MYNJ_PROFILE_LINK: https://my.state.nj.us/portal/Desktop

  integration-tests:
    parameters:
      enable-dashboard:
        type: boolean
        default: false
      suite:
        type: string
    docker:
      - image: cimg/node:14.18.2-browsers
    steps:
      - set-cypress-env-vars
      - attach_workspace:
            at: .
      - configure-and-build
      - install-chrome
      - perform-integration-tests:
          enable-dashboard: << parameters.enable-dashboard >>
          suite: << parameters.suite >>
      - store-deploy-cache
    environment:
      CYPRESS_API_BASE_URL: http://localhost:5000/local

  smoke-tests:
    parameters:
      enable-dashboard:
        type: boolean
        default: false
      suite:
        type: string
    docker:
      - image: cimg/node:14.18.2-browsers
    steps:
      - attach_workspace:
            at: .
      - set-dev-env-vars
      - configure-smoke-test
      - install-chrome
      - perform-smoke-tests:
          enable-dashboard: << parameters.enable-dashboard >>
          suite: << parameters.suite >>

workflows:
  release-pipeline:
    jobs:
      - staging-hold:
          type: approval
          filters:
            branches:
              only:
                - /^release-.*/
      - deploy-staging:
          name: staging-deploy
          filters:
            branches:
              only:
                - /^release-.*/
          requires:
            - staging-hold
      - production-hold:
          type: approval
          filters:
            branches:
              only:
                - /^release-.*/
          requires:
            - staging-deploy
      - prepare-release:
          filters:
            branches:
              only:
                - /^release-.*/
          requires:
            - production-hold
      - deploy-production:
          name: production-deploy
          filters:
            branches:
              only:
                - /^release-.*/
          requires:
            - prepare-release

  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^release-.*/
      - lint:
          filters:
            branches:
              ignore:
                - /^release-.*/
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 1
          suite: group1
          filters:
            branches:
              ignore:
                - main
                - /^release-.*/
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 2
          suite: group2
          filters:
            branches:
              ignore:
                - main
                - /^release-.*/
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 3
          suite: group3
          filters:
            branches:
              ignore:
                - main
                - /^release-.*/
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 1
          enable-dashboard: true
          suite: group1
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 2
          enable-dashboard: true
          suite: group2
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - integration-tests:
          name: Integration Tests - Group 3
          enable-dashboard: true
          suite: group3
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - deploy-dev:
          name: dev-deploy
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - smoke-tests:
          name: Deployment Smoke Tests
          enable-dashboard: true
          suite: smoke
          filters:
            branches:
              only:
                - main
          requires:
            - dev-deploy
