backend:
  name: github
  repo: newjersey/navigator.business.nj.gov
  branch: main
  base_url: https://cubukxpyt9.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /dev/api/cms/auth
  use_graphql: true
  squash_merges: true
  commit_messages:
    create: "feat: creating {{collection}} {{slug}}"
    update: "fix: updating {{collection}} {{slug}}"
publish_mode: editorial_workflow
media_folder: web/public/img
logo_url: https://dev.d1fxpe8xsdfr62.amplifyapp.com/img/Navigator-logo.svg
public_folder: web/public
collections:
  - label: Roadmap Add-ons
    name: addons
    folder: "content/src/roadmaps/add-ons"
    extension: "json"
    identifier_field: "{{filename}}"
    summary: "{{filename}}"
    fields:
      - label: Roadmap Steps
        name: roadmapSteps
        widget: list
        summary: "Step {{step}} - {{task}}"
        fields:
          - label: Roadmap Step
            name: step
            widget: relation
            collection: "settings"
            search_fields: ["steps.*.name"]
            value_field: "steps.*.step_number"
            display_fields: ["steps.*.name"]
          - label: Weight
            name: weight
            widget: number
          - label: Task
            name: task
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]
      - label: Task Overrides
        name: modifications
        widget: list
        summary: "{{taskToReplaceFilename}}"
        fields:
          - label: Task To Replace
            name: taskToReplaceFilename
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]
          - label: Modified Task
            name: replaceWithFilename
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]

  - name: "roadmaps"
    label: "Industry Roadmaps"
    folder: "content/src/roadmaps/industries"
    slug: "{{id}}"
    identifier_field: "{{id}}"
    extension: "json"
    create: true
    delete: true
    format: "json"
    summary: "{{filename}}"
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Home Based
        name: canBeHomeBased
        widget: boolean
        default: false
      - label: Liquor License
        name: isLiquorLicenseApplicable
        widget: boolean
        default: false
      - label: Mobile Location
        name: isMobileLocation
        widget: boolean
        default: false
      - label: Reseller
        name: canBeReseller
        widget: boolean
        default: false
      - label: Additional Search Teams
        name: additionalSearchTerms
        widget: string
        required: false
      - label: Id / Filename
        name: id
        widget: string
      - label: Roadmap Steps
        name: roadmapSteps
        widget: list
        summary: "Step {{step}} - {{task}}"
        fields:
          - label: Roadmap Step
            name: step
            widget: relation
            collection: "settings"
            search_fields: ["steps.*.name"]
            value_field: "steps.*.step_number"
            display_fields: ["steps.*.name"]
          - label: Weight
            name: weight
            widget: number
          - label: Task
            name: task
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]
      - label: Task Overrides
        name: modifications
        widget: list
        summary: "{{taskToReplaceFilename}}"
        fields:
          - label: Task To Replace
            name: taskToReplaceFilename
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]
          - label: Modified Task
            name: replaceWithFilename
            widget: "relation"
            collection: "tasks"
            search_fields: ["{{filename}}", "name", "urlSlug"]
            value_field: "{{filename}}"
            display_fields: ["{{filename}}"]

  - name: "tasks"
    label: "Tasks"
    folder: "content/src/roadmaps/tasks"
    summary: "{{filename}} - [{{id}}] - {{name}} - {{industryId}}"
    identifier_field: "{{filename}}"
    slug: "{{fields.filename}}"
    delete: true
    sortable_fields: ["id", "name", "{{urlSlug}}", "industryId"]
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Url Slug", name: "urlSlug", widget: "string" }
      - { label: "Filename", name: "filename", widget: "slug", required: false  }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Call To Action Link", name: "callToActionLink", widget: "string", required: false }
      - { label: "Call To Action Text", name: "callToActionText", widget: "string", required: false }
      - label: Industry
        name: industryId
        widget: "relation"
        collection: "roadmaps"
        search_fields: ["{{id}}"]
        value_field: "{{id}}"
        display_fields: ["{{id}}"]
        required: false

  - name: "filings"
    label: "Filings Content"
    folder: "content/src/filings"
    summary: "/{{urlSlug}} - [{{id}}] - {{name}}"
    identifier_field: "{{urlSlug}}"
    slug: "{{urlSlug}}"
    delete: true
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Url Slug / Filename", name: "urlSlug", widget: "slug" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Call To Action Link", name: "callToActionLink", widget: "string", required: false }
      - { label: "Call To Action Text", name: "callToActionText", widget: "string", required: false }
      
  - name: "contextual-information"
    label: "Contextual Information"
    folder: "content/src/display-content/contextual-information"
    summary: "{{filename}}"
    identifier_field: "{{fields.slug}}"
    slug: "{{fields.slug}}"
    delete: true
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Filename", name: "slug", widget: "slug", required: false }

  - name: "onboarding-content"
    label: "Onboarding Content"
    folder: "content/src/display-content/onboarding"
    summary: "{{filename}}"
    identifier_field: "{{fields.slug}}"
    slug: "{{fields.slug}}"
    delete: false
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Filename", name: "slug", widget: "slug", required: false   }
      - { label: "Placeholder", name: "placeholder", widget: "string", required: false }
      - { label: "Yes Button Copy", name: "radioButtonYesText", widget: "string", required: false }
      - { label: "No Button Copy", name: "radioButtonNoText", widget: "string", required: false }

  - name: "post-onboarding-content"
    label: "Post Onboarding Content"
    folder: "content/src/display-content/post-onboarding"
    summary: "{{filename}}"
    identifier_field: "{{fields.slug}}"
    slug: "{{fields.slug}}"
    delete: false
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Filename", name: "slug", widget: "slug", required: false   }
      - { label: "Question Copy", name: "radioQuestion", widget: "string", required: false }
      - { label: "Yes Button Copy", name: "radioYes", widget: "string", required: false }
      - { label: "No Button Copy", name: "radioNo", widget: "string", required: false }
      - { label: "No Button Content", name: "radioNoContent", widget: "string", required: false }
      
  - name: "business-formation"
    label: "Business Formation"
    folder: "content/src/display-content/business-formation"
    summary: "{{filename}}"
    identifier_field: "{{fields.slug}}"
    slug: "{{fields.slug}}"
    delete: false
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Filename", name: "slug", widget: "slug", required: false   }
      - { label: "Radio Button Number Text", name: "radioButtonNumberText", widget: "string", required: false }
      - { label: "Radio Button Manual Text", name: "radioButtonManualText", widget: "string", required: false }
      - { label: "Placeholder", name: "placeholder", widget: "string", required: false }
      - { label: "cost", name: "cost", widget: "string", required: false }
      - { label: "Optional Label", name: "optionalLabel", widget: "string", required: false }

  - name: "roadmap-content"
    label: "Roadmap Content"
    folder: "content/src/display-content/roadmap"
    summary: "{{filename}}"
    identifier_field: "{{fields.slug}}"
    slug: "{{fields.slug}}"
    delete: false
    create: true
    editor:
      preview: true
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Filename", name: "slug", widget: "slug", required: false   }

  - name: "settings"
    label: "Roadmap Settings"
    delete: false
    files:
      - label: "Steps"
        name: "steps"
        file: "content/src/roadmaps/steps.json"
        fields:
          - label: steps
            name: steps
            widget: list
            summary: "{{name}}"
            fields:
              - label: Name
                name: name
                widget: string
              - label: Section
                name: section
                widget: select
                options: ["PLAN", "START"]
              - label: Time Estimate
                name: timeEstimate
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Number
                name: step_number
                widget: number
                min: 0
                value_type: int
