name: "Deploy To Testing Environment"
description:
  "Runs deploy-setup, packages the WebApp Docker image, and deploys the Testing ECS service."

runs:
  using: "composite"
  steps:
    - name: Deploy Setup
      uses: ./.github/actions/deploy-setup
    - name: Package WebApp Docker Image
      uses: ./.github/actions/package-webapp-docker
      with:
        image-name: bfs-navigator-testing

    - name: Deploy WebApp to ECS
      shell: bash
      run: |
        aws ecs update-service --cluster bfs_container_cluster \
          --service bfs-navigator-testing --region "$AWS_REGION" \
          --force-new-deployment
