name: "Deploy CDK"
description: "Clears CDK context, runs CDK bootstrap, and deploys all stacks."

inputs:
  import_tables:
    description: "Enable Dynamo Table ownership mode import (default: false)"
    required: false
    default: "false"

  run_import_command:
    description: "Run the CDK import for DynamoDB Tables"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Clear CDK Context
      shell: bash
      run: |
        yarn workspace @businessnjgovnavigator/api-cdk cdk context --clear

    - name: CDK Bootstrap
      shell: bash
      run: |
        echo "Running CDK bootstrap for stage: $STAGE ..."
        yarn workspace @businessnjgovnavigator/api-cdk cdk bootstrap aws://$AWS_ACCOUNT_ID/us-east-1 \
          --bootstrap-bucket-name cdk-biz-nj-assets-$AWS_ACCOUNT_ID-us-east-1 \
          --qualifier biz-nj \
          --trust arn:aws:iam::$AWS_ACCOUNT_ID:user/system/bfs-navigator \
          --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess || \
          echo "Bootstrap already completed or not required."

    - name: Import DynamoDB tables in CDK DataStack
      if: ${{ inputs.import_tables == 'true' && inputs.run_import_command =='true' }}
      shell: bash
      run: |
        echo "Running CDK import for DynamoDB tables in stage: $STAGE"
        yarn workspace @businessnjgovnavigator/api-cdk cdk deploy DataStack-${{ env.STAGE }} \
          --import-existing-resources \
          --qualifier biz-nj \
          --verbose \
          --region us-east-1 \
          --require-approval never

    - name: Deploy IAM Stack (Temp Step)
      shell: bash
      run: |
        echo "Running CDK for IamStack in stage: $STAGE"
        yarn workspace @businessnjgovnavigator/api-cdk cdk deploy IamStack-${{ env.STAGE }} \
          --qualifier biz-nj \
          --verbose \
          --region us-east-1 \
          --require-approval never

    - name: Import Backup resources in CDK BackupStack
      shell: bash
      run: |
        if [ "$STAGE" = "dev" ]; then
          BACKUP_STACK="BackupStack-shared-lowerEnv"
        elif [ "$STAGE" = "staging" ] || [ "$STAGE" = "prod" ]; then
          BACKUP_STACK="BackupStack-$STAGE"
        else
          echo "No BackupStack import required for stage: $STAGE"
          exit 0
        fi
        echo "Importing backup resources for stage: $STAGE"
        yarn workspace @businessnjgovnavigator/api-cdk cdk import "$BACKUP_STACK" \
          --qualifier biz-nj \
          --verbose \
          --region us-east-1 \
          --require-approval never

    - name: Deploy CDK
      shell: bash
      run: |
        yarn workspace @businessnjgovnavigator/api-cdk cdk deploy \
          --all \
          --qualifier biz-nj \
          --verbose \
          --region us-east-1 \
          --require-approval never
