/**
 * Default configuration object with safe fallback values
 * This ensures getMergedConfig() always returns a valid ConfigType
 * even during SSG when JSON imports may not be fully loaded
 */
export const getDefaultConfig = (): Record<string, unknown> => ({
  abcEmergencyTripPermit: {
    fields: {
      additionalEmail: "",
      carrier: "",
      deliveryAddress: "",
      deliveryCity: "",
      deliveryCountry: "",
      deliverySiteName: "",
      deliveryStateProvince: "",
      deliveryZipPostalCode: "",
      payerAddress1: "",
      payerAddress2: "",
      payerCity: "",
      payerCompanyName: "",
      payerCountry: "",
      payerEmail: "",
      payerFirstName: "",
      payerLastName: "",
      payerPhoneNumber: "",
      payerStateAbbreviation: "",
      payerZipCode: "",
      permitDate: "",
      permitStartTime: "",
      pickupAddress: "",
      pickupCity: "",
      pickupCountry: "",
      pickupSiteName: "",
      pickupStateProvince: "",
      pickupZipPostalCode: "",
      requestorAddress1: "",
      requestorAddress2: "",
      requestorCity: "",
      requestorCountry: "",
      requestorEmail: "",
      requestorFirstName: "",
      requestorLastName: "",
      requestorPhone: "",
      requestorStateProvince: "",
      requestorZipPostalCode: "",
      textMsgMobile: "",
      vehicleCountry: "",
      vehicleLicensePlateNum: "",
      vehicleMake: "",
      vehicleStateProvince: "",
      vehicleVinSerial: "",
      vehicleYear: "",
    },
    nextStepText: "",
    previousStepText: "",
    steps: {
      billing: {
        additionalEmailDownloadLinkCheckboxLabel: "",
        billingSection: "",
        onlineProcessFeeLineItem: "",
        pdfAttachCheckboxLabel: "",
        permitSection: "",
        permitSubheader: "",
        servicesSection: "",
        textMessageDownloadLinkCheckboxLabel: "",
        totalFeeLineItem: "",
        tripPermitFeeInfo: "",
        tripPermitFeeLineItem: "",
      },
      instructions: {
        applicationDetails: "",
        applicationHeader: "",
        applicationInstructionsDescription: "",
        buttonText: "",
        description: "",
        helpText: "",
      },
      requestor: {
        requestorSection: "",
        requestorSectionSubHeading: "",
        vehicleSection: "",
      },
      review: {
        alternateEmail: "",
        apiErrorText: "",
        confirmationEmail: "",
        errorSubmitText: "",
        infoAlertText: "",
        permitAttach: "",
        permitTextMessage: "",
      },
      trip: {
        deliverySiteSection: "",
        informationalCallOutText: "",
        pickupSiteSection: "",
        subHeader: "",
      },
    },
    submitText: "",
    taskName: "",
  },
  accountSetup: {
    default: {
      body: "",
      header: "",
      submitButton: "",
    },
    errorAlert: "",
    existingAccount: {
      body: "",
      header: "",
      submitButton: "",
    },
  },
  anytimeActionReinstatementAndLicenseCalendarEventStatusDefaults: {
    licenseExpirationHeaderText: "",
    licenseLastUpdatedText: "",
    licenseStatusHeaderText: "",
  },
  arrayOfFundingAgencies: [],
  arrayOfOwnershipTypes: [],
  arrayOfSectors: [],
  arrayOfTaskAgencies: [],
  arrayOfTaxClearanceCertificateIssuingAgencies: [],
  autosaveDefaults: {
    savedText: "",
    savingText: "",
  },
  betaBar: {
    betaMainText: "",
    betaModalButtonText: "",
  },
  businessStructurePrompt: {
    businessStructureNotSelectedAlertText: "",
    buttonText: "",
    notCompletedTaskPromptAnyTask: "",
    notCompletedTaskPromptBusinessStructureTask: "",
  },
  businessStructureTask: {
    ariaLabelText: "",
    completedHeader: "",
    completedTooltip: "",
    radioQuestionHeader: "",
    saveButton: "",
    successMessage: "",
    uncompletedTooltip: "",
  },
  calloutAlerts: {
    calloutAlertGroupTitle: "",
    error: "",
    info: "",
    note: "",
    success: "",
    warning: "",
  },
  calloutDefaults: {
    amountIconAriaLabel: "",
    conditionalHeadingDefaultText: "",
    emailIconAriaLabel: "",
    filingTypeIconAriaLabel: "",
    frequencyIconAriaLabel: "",
    informationalHeadingDefaultText: "",
    phoneIconAriaLabel: "",
    quickReferenceHeadingDefaultText: "",
    warningHeadingDefaultText: "",
  },
  cannabisApplyForLicense: {
    annualBottomOfTask: "",
    annualGeneralRequirements: "",
    applicationPageHelperText: "",
    applicationQuestionsText: "",
    backToFirstTabButton: "",
    businessSizeHeader: "",
    conditionalBottomOfTask: "",
    conditionalGeneralRequirements: "",
    diverselyOwnedLabel: "",
    diverselyOwnedRequirements: "",
    generalApplicationNeeds: "",
    impactZoneLabel: "",
    impactZoneRequirements: "",
    microbusinessApplicationNeeds: "",
    microbusinessRadioNo: "",
    microbusinessRadioQuestion: "",
    microbusinessRadioYes: "",
    microbusinessRequirements: "",
    priorityStatusApplicationNeeds: "",
    priorityStatusHeader: "",
    priorityStatusNoneSelectedText: "",
    priorityStatusText: "",
    sbeLabel: "",
    socialEquityRequirements: "",
    viewRequirementsButton: "",
  },
  cannabisEligibilityModal: {
    eligibleModalBody: "",
    eligibleModalCancelButton: "",
    eligibleModalContinueButton: "",
    eligibleModalTitle: "",
  },
  cannabisPriorityStatus: {
    backButtonText: "",
    certificationButtonLink: "",
    certificationButtonText: "",
    completeTaskProgressButtonText: "",
    dropdownCTAButtonText: "",
    greenBoxHeadingText: "",
    greenBoxMinorityOrWomenText: "",
    greenBoxSocialEquityText: "",
    greenBoxVeteranText: "",
    impactZone: "",
    impactZoneHeaderText: "",
    impactZoneText: "",
    minorityOrWomenHeaderText: "",
    minorityWomenOrVeteran: "",
    minorityWomenOwnedRequirements: "",
    nextButtonText: "",
    noPriorityStatusCheckboxText: "",
    noPriorityStatusText: "",
    phrase1: "",
    phrase2: "",
    phrase3: "",
    secondTabDescriptionText: "",
    secondTabHeaderText: "",
    socialEquity: "",
    socialEquityButtonLink: "",
    socialEquityButtonText: "",
    socialEquityHeaderText: "",
    socialEquityRequirements: "",
    tab1Content: "",
    veteranHeaderText: "",
    veteranOwnedRequirements: "",
  },
  checkAccountEmailPage: {
    defaultErrorMessage: "",
    emailNotFoundError: "",
    header: "",
    inputButton: "",
    inputLabel: "",
    intercomChatText: "",
    invalidEmailError: "",
    linkAccountLinkText: "",
    needHelpText: "",
    noAccountText: "",
    serviceNotAvailableError: "",
  },
  cigaretteLicenseConfirmation: {
    amountPaid: "",
    businessAddressLine1: "",
    businessAddressLine2: "",
    cantCompleteFilingAlert: "",
    cantCompleteFilingMessage1: "",
    cantCompleteFilingMessage2: "",
    confirmationNumber: "",
    dateSubmitted: "",
    issuingAgency: "",
    licenseeInformationHeader: "",
    mailingAddressLine1: "",
    mailingAddressLine2: "",
    needHelpHeader: "",
    needHelpInfo: "",
    paymentSuccessfulHeader: "",
    paymentSuccessfulInfo: "",
    startLiveChatButton: "",
    submissionDetails: "",
    suppliers: "",
    tryAgainButton: "",
    whatHappensNextBullet1: "",
    whatHappensNextBullet2: "",
    whatHappensNextHeader: "",
    whatHappensNextInfo: "",
  },
  cigaretteLicenseShared: {
    alertFieldNames: {
      addressCity: "",
      addressLine1: "",
      addressLine2: "",
      addressState: "",
      addressZipCode: "",
      businessName: "",
      contactEmail: "",
      contactName: "",
      contactPhoneNumber: "",
      mailingAddressCity: "",
      mailingAddressLine1: "",
      mailingAddressLine2: "",
      mailingAddressState: "",
      mailingAddressZipCode: "",
      responsibleOwnerName: "",
      salesInfoStartDate: "",
      salesInfoSupplier: "",
      signature: "",
      signerName: "",
      signerRelationship: "",
      taxId: "",
      tradeName: "",
    },
    alertInvalidFields: "",
    alertPaymentError: "",
    alertServiceUnavailable: "",
    issuingAgencyLabelText: "",
    issuingAgencyText: "",
    stepperFourLabel: "",
    stepperOneLabel: "",
    stepperThreeLabel: "",
    stepperTwoLabel: "",
  },
  cigaretteLicenseStep1: {
    alert: "",
    content: "",
    continueButtonText: "",
  },
  cigaretteLicenseStep2: {
    backButtonText: "",
    businessAddressDescription: "",
    businessAddressHeader: "",
    businessNameErrorText: "",
    businessNameText: "",
    contactInformationDescription: "",
    contactInformationHeader: "",
    fields: {
      contactEmail: {
        errorRequiredText: "",
        label: "",
      },
      contactName: {
        errorRequiredText: "",
        label: "",
      },
      contactPhoneNumber: {
        errorRequiredText: "",
        label: "",
      },
      mailingAddressCity: {
        errorRequiredText: "",
        label: "",
      },
      mailingAddressLine1: {
        errorRequiredText: "",
        errorValidationText: "",
        label: "",
      },
      mailingAddressLine2: {
        errorValidationText: "",
        label: "",
      },
      mailingAddressState: {
        errorRequiredText: "",
        label: "",
      },
      mailingAddressZipCode: {
        errorRequiredText: "",
        errorValidationText: "",
        errorValidationTextAlt: "",
        label: "",
      },
    },
    licenseeInformationDescription: "",
    licenseeInformationHeader: "",
    mailingAddressDescription: "",
    mailingAddressHeader: "",
    mailingIsSameCheckbox: "",
    nextButtonText: "",
  },
  cigaretteLicenseStep3: {
    backButtonText: "",
    fields: {
      selectASupplier: {
        errorRequiredText: "",
        errorValidationText: "",
        label: "",
      },
      startDateOfSales: {
        errorRequiredText: "",
        errorValidationText: "",
        label: "",
      },
    },
    nextButtonText: "",
    salesInformationHeader: "",
  },
  cigaretteLicenseStep4: {
    alertBeforeSubmit: "",
    backButtonText: "",
    businessAddressHeader: "",
    contactInformationHeader: "",
    costLabelText: "",
    costValue: "",
    feesSubjectToChange: "",
    issuingAgency: "",
    mailingAddressHeader: "",
    paymentHeader: "",
    retailOverTheCounterLicenseLabelText: "",
    reviewAndPayHeader: "",
    reviewItems: {
      businessAddressCity: "",
      businessAddressLine1: "",
      businessAddressLine2: "",
      businessAddressState: "",
      businessAddressZipCode: "",
      businessName: "",
      contactEmail: "",
      contactName: "",
      contactPhoneNumber: "",
      mailingAddressCity: "",
      mailingAddressLine1: "",
      mailingAddressLine2: "",
      mailingAddressState: "",
      mailingAddressZipCode: "",
      salesInfoStartDate: "",
      salesInfoSupplier: "",
      taxId: "",
    },
    salesInformationHeader: "",
    servicesLabelText: "",
    signerNameErrorText: "",
    signerNameLabel: "",
    signerRelationshipErrorText: "",
    signerRelationshipLabel: "",
    signersConfirmationText: "",
    signersDescription: "",
    signersHeader: "",
    signLabel: "",
    submitAndPayButtonText: "",
    totalLabelText: "",
  },
  crtkTask: {
    businessCityError: "",
    businessNameError: "",
    businessNameLabel: "",
    businessStreetAddressError: "",
    businessStreetAddressLabel: "",
    businessZipError: "",
    certainIndustriesLink: "",
    cityLabel: "",
    einLabel: "",
    einOptionalText: "",
    errorTextFieldsRequired: "",
    errorTextForm: "",
    errorTextNotFound: "",
    errorTextSearchFailed: "",
    federalInfoText: "",
    federalInfoTitle: "",
    federalLinkText: "",
    helperText: "",
    introText: "",
    lastUpdatedText: "",
    stateLabel: "",
    submitText: "",
    titleText: "",
    warningText: "",
    warningTitle: "",
    zipLabel: "",
  },
  dashboardAnytimeActionDefaults: {
    commonBusinessTasksHeader: "",
    defaultHeaderText: "",
    recommendedForYouCategoryHeader: "",
    searchFieldHeaderText: "",
    searchFieldHintText: "",
    searchHasNoOptionsText: "",
  },
  dashboardDefaults: {
    additionalBusinessSnackbarBody: "",
    additionalBusinessSnackbarHeader: "",
    calendarAddDateMd: "",
    calendarEmptyDescriptionMarkdown: "",
    calendarFeedbackButtonText: "",
    calendarFilingDueDateLabel: "",
    calendarGridViewButton: "",
    calendarHeader: "",
    calendarLegalText: "",
    calendarListViewButton: "",
    calendarListViewMoreButton: "",
    calendarSnackbarBody: "",
    calendarSnackbarHeading: "",
    calendarTooltip: "",
    certificationsSnackbarBody: "",
    certificationsSnackbarHeading: "",
    certificationTagText: "",
    completeRequiredTasksText: "",
    congratulatoryModalBody: "",
    congratulatoryModalHeader: "",
    congratulatoryModalLinkText: "",
    congratulatoryModalTitle: "",
    deferredOnboardingSnackbarBody: "",
    deferredOnboardingSnackbarHeader: "",
    emptyCalendarTitleText: "",
    emptyOpportunitiesHeader: "",
    emptyOpportunitiesRemoteSellerWorkerText: "",
    emptyOpportunitiesText: "",
    fundingSnackbarBody: "",
    fundingSnackbarHeading: "",
    fundingTagText: "",
    hiddenOpportunitiesHeader: "",
    hiddenTasksText: "",
    hideOpportunityText: "",
    hideTaskText: "",
    learnMoreFundingOpportunitiesLink: "",
    learnMoreFundingOpportunitiesText: "",
    mobileFirstTabText: "",
    mobileSecondTabText: "",
    needsAccountSnackbarBody: "",
    needsAccountSnackbarTitle: "",
    opportunitiesAndDeadlinesBody: "",
    opportunitiesAndDeadlinesHeading: "",
    removedBusinessSnackbarBody: "",
    removedBusinessSnackbarTitle: "",
    sectorModalBody: "",
    sectorModalCancelButton: "",
    sectorModalSaveButton: "",
    sectorModalTitle: "",
    showTaskText: "",
    sidebarHeading: "",
    taxRegistrationSnackbarBody: "",
    taxRegistrationSnackbarHeading: "",
    timeDelayBetweenMultipleSnackbars: 0,
    unHideOpportunityText: "",
    viewLessFilingsButton: "",
    viewMoreFilingsButton: "",
  },
  dashboardHeaderDefaults: {
    defaultHeaderText: "",
    genericStarterKitText: "",
    noUserNameHeaderText: "",
    personalizeMyTasksButtonText: "",
    starterKitText: "",
  },
  dashboardRoadmapHeaderDefaults: {
    DomesticEmployerRoadmapTasksHeaderText: "",
    RoadmapTasksHeaderText: "",
  },
  DbaFormationTask: {
    dbaCtaModalBody: "",
    dbaCtaModalCancelButtonText: "",
    dbaCtaModalContinueButtonText: "",
    dbaCtaModalHeader: "",
    descriptionShownWithWarning: "",
    warningText: "",
  },
  deferredLocation: {
    deferredOnboardingSaveButtonText: "",
    description: "",
    editText: "",
    header: "",
    removeText: "",
    successText: "",
  },
  determineNaicsCode: {
    ariaLabelText: "",
    findCodeBodyText: "",
    findCodeHeader: "",
    hasSavedCodeHeader: "",
    invalidValidationErrorText: "",
    lengthValidationErrorText: "",
    missingNAICSCodePlaceholder: "",
    naicsDescriptionURL: "",
    naicsLink: "",
    saveButtonText: "",
    successMessage: "",
    suggestedCodeBodyText: "",
  },
  ein: {
    ariaLabelText: "",
    descriptionText: "",
    saveButtonText: "",
    successText: "",
  },
  elevatorRegistrationSearchTask: {
    address1Label: "",
    address2Label: "",
    errorTextFieldsRequired: "",
    errorTextNoElevatorRegistrations: "",
    errorTextNoPropertyInterestFound: "",
    errorTextSearchFailed: "",
    informationalIncomplete: "",
    informationalInReview: "",
    informationalRejected: "",
    informationalReturned: "",
    municipalityLabel: "",
    registrationApplicationFoundText: "",
    registrationCallToActionPrimaryText: "",
    registrationCallToActionSecondaryText: "",
    registrationDeviceCountText: "",
    registrationFoundIncompleteReturnedText: "",
    registrationFoundInReviewText: "",
    registrationInReviewMessage: "",
    registrationRejectedOrReturnedMessage: "",
    registrationRequestDateText: "",
    registrationSearchPrompt: "",
    registrationStatusText: "",
    registrationTab1Text: "",
    registrationTab2Text: "",
    stateLabel: "",
    submitText: "",
  },
  elevatorViolationsCard: {
    violationNoticeCTA: "",
    violationNoticeCTALink: "",
    violationNoticeMessage: "",
  },
  employerRates: {
    baseWeekAmountLabelText: "",
    belowSectionHeaderText: "",
    businessNameErrorLink: "",
    configRatesSuccessHeaderText: "",
    diLabelText: "",
    disabilityInsuranceRow: "",
    dolEinAlertLabelText: "",
    dolEinErrorText: "",
    dolEinLabelText: "",
    editQuarterButtonText: "",
    employerAccessFalseText: "",
    employerAccessHeaderText: "",
    employerAccessNoBodyText: "",
    employerAccessNoButtonLink: "",
    employerAccessNoButtonText: "",
    employerAccessText: "",
    employerAccessTrueText: "",
    employerAccessYesButtonText: "",
    employerRatesTableHeaderText: "",
    familyLeaveInsuranceRow: "",
    fliLabelText: "",
    healthcareSubsidyFundRow: "",
    healthcareSubsidyFundTooltipText: "",
    noAccountErrorText: "",
    noEmployerRatesFliText: "",
    numberOfBaseWeeksLabelText: "",
    quarterDropdownLabelText: "",
    quarterDropdownTooltipText: "",
    quarterFourLabel: "",
    quarterOneLabel: "",
    quarterThreeLabel: "",
    quarterTwoLabel: "",
    sectionHeaderText: "",
    serverErrorText: "",
    serverErrorTryAgainText: "",
    successAlertText: "",
    taxableWageBaseDiFliLabelText: "",
    taxableWageBaseLabelText: "",
    totalContributionsSuccessHeaderText: "",
    uiHcWFLabelText: "",
    unemploymentInsuranceRow: "",
    workerRatesTableHeaderText: "",
    workforceDevelopmentRow: "",
  },
  envQuestionPage: {
    air: {
      mediaAreaLink: "",
      mediaAreaText: "",
      questionnaireOptions: {
        constructionActivities: "",
        emitEmissions: "",
        emitPollutants: "",
        noAir: "",
      },
    },
    drinkingWater: {
      mediaAreaLink: "",
      mediaAreaText: "",
      questionnaireOptions: {
        combinedWellCapacity: "",
        noDrinkingWater: "",
        ownWell: "",
        potableWater: "",
        wellDrilled: "",
      },
    },
    generic: {
      ariaContextEnvStepperLabels: "",
      ariaContextInlineDialogActive: "",
      ariaContextInlineDialogInactive: "",
      backButtonText: "",
      buttonText: "",
      endingButtonText: "",
      errorText: "",
      footerText: "",
      question: "",
      startingButtonText: "",
      title: "",
    },
    instructions: {
      lineOne: "",
      lineThree: "",
      lineTwoNotText: "",
      lineTwoPtOne: "",
      lineTwoPtTwo: "",
    },
    land: {
      mediaAreaLink: "",
      mediaAreaText: "",
      questionnaireOptions: {
        constructionActivities: "",
        noLand: "",
        propertyAssessment: "",
        siteImprovementWasteLands: "",
        takeOverExistingBiz: "",
      },
    },
    waste: {
      mediaAreaLink: "",
      mediaAreaText: "",
      questionnaireOptions: {
        compostWaste: "",
        constructionDebris: "",
        hazardousMedicalWaste: "",
        noWaste: "",
        transportWaste: "",
        treatProcessWaste: "",
      },
    },
    wasteWater: {
      mediaAreaLink: "",
      mediaAreaText: "",
      questionnaireOptions: {
        industrialWaste: "",
        localSewage: "",
        needsTreatment: "",
        noWasteWater: "",
        planningConstruction: "",
        sanitaryWaste: "",
        septicSystem: "",
        stormWaterDischarge: "",
        streamsRiversOrLakes: "",
        takeoverIndustrialStormWaterPermit: "",
      },
    },
  },
  envResultsPage: {
    contactDep: {
      air: {
        bodyLink: "",
        contact: {
          email: "",
          form: "",
          phone: "",
          phoneInfo: "",
        },
        heading: "",
      },
      body: "",
      drinkingWater: {
        bodyLink: "",
        contact: {
          email: "",
          form: "",
          phone: "",
          phoneInfo: "",
        },
        heading: "",
      },
      land: {
        bodyLink: "",
        contact: {
          email: "",
          form: "",
          phone: "",
          phoneInfo: "",
        },
        heading: "",
      },
      title: "",
      waste: {
        bodyLink: "",
        contact: {
          email: "",
          form: "",
          phone: "",
          phoneInfo: "",
        },
        heading: "",
      },
      wasteWater: {
        bodyLink: "",
        contact: {
          email: "",
          form: "",
          phone: "",
          phoneInfo: "",
        },
        heading: "",
      },
    },
    editInfo: "",
    editText: "",
    lowApplicability: {
      callout: "",
      calloutRedo: "",
      summaryLineOne: "",
      summaryLineTwo: "",
    },
    personalizedSupport: {
      body: "",
      contact: "",
      contactSbapButton: "",
      directContactInfo: "",
      emailErrorAlertText: "",
      emailErrorText: "",
      emailLabel: "",
      generalErrorAlertText: "",
      generalErrorText: "",
      submissionCadence: "",
      title: "",
    },
    seeYourResponses: {
      title: "",
    },
    summary: {
      mediaAreaText: {
        air: "",
        drinkingWater: "",
        land: "",
        waste: "",
        wasteWater: "",
      },
      partFour: "",
      partOne: "",
      partThree: "",
      partTwo: "",
    },
    title: "",
  },
  filingDefaults: {
    additionalInfo: "",
    beforeDueDateText: "",
    dueDateToolTip: "",
    extensionTagText: "",
    filingFrequency: "",
    filingMethod: "",
    formText: "",
    issuingAgencyText: "",
    lateFilingsMarkdown: "",
    lateFilingsTitle: "",
    onlineOrPhoneTaxFilingMethod: "",
    onlineRequiredTaxFilingMethod: "",
    onlineTaxFilingMethod: "",
    paperOrMailOnlyTaxFilingMethod: "",
    taxRateTitle: "",
    treasuryLinkText: "",
  },
  footer: {
    byTheOfficeOfInnovationText: "",
    creditLink: "",
    creditLinkText: "",
    creditText: "",
    facebookLink: "",
    gitHubLink: "",
    linkOne: "",
    linkOneText: "",
    linkTwo: "",
    linkTwoText: "",
    madeWithLoveByTheOfficeOfInnovationAriaLabel: "",
    madeWithText: "",
    officeExternalText: "",
    officeLink: "",
  },
  formation: {
    addressModal: {
      addressCity: {
        error: "",
        label: "",
      },
      addressLine1: {
        error: "",
        label: "",
      },
      addressLine2: {
        label: "",
      },
      addressState: {
        error: "",
        label: "",
      },
      addressZipCode: {
        error: "",
        label: "",
      },
      name: {
        error: "",
        label: "",
      },
    },
    checkNameReservation: {
      alreadyReservedAlertHeader: "",
      alreadyReservedAlertInfo: "",
      cancelNameHeader: "",
      cancelNameStep1: "",
      cancelNameStep2: "",
      cancelNameStep3: "",
      cancelNameStep4: "",
      didYouUseFormRadio: {
        label: "",
        option1: "",
        option2: "",
      },
      header: "",
      howWouldYouLikeToProceedRadio: {
        label: "",
        option1: "",
        option2: "",
        option3: "",
      },
      keepNameAddressLine1: "",
      keepNameAddressLine2: "",
      keepNameAddressLine3: "",
      keepNameHeader: "",
      keepNameStep1: "",
      keepNameStep2: "",
      keepNameStep3: "",
      registerDifferentNameHeader: "",
      registerDifferentNameLine1: "",
      registerDifferentNameLine2: "",
    },
    errorBanner: {
      apiResubmitText: "",
      errorOnStep: "",
      genericApiError: "",
      incompleteStepsError: "",
    },
    fields: {
      additionalProvisions: {
        addAnotherButtonText: "",
        addButtonText: "",
        body: "",
        label: "",
        secondaryLabel: "",
      },
      addressCity: {
        error: "",
        label: "",
      },
      addressCountry: {
        error: "",
        label: "",
      },
      addressLine1: {
        error: "",
        label: "",
      },
      addressLine2: {
        error: "",
        label: "",
      },
      addressMunicipality: {
        error: "",
        infoAlert: "",
        label: "",
      },
      addressProvince: {
        error: "",
        label: "",
      },
      addressState: {
        error: "",
        label: "",
      },
      addressZipCode: {
        error: "",
        foreign: {
          errorIntl: "",
          errorUS: "",
          label: "",
        },
        label: "",
      },
      agentEmail: {
        error: "",
        label: "",
      },
      agentName: {
        error: "",
        label: "",
      },
      agentNumber: {
        error: "",
        helperText: "",
        label: "",
      },
      agentOfficeAddressCity: {
        error: "",
        label: "",
      },
      agentOfficeAddressLine1: {
        error: "",
        label: "",
      },
      agentOfficeAddressLine2: {
        label: "",
      },
      agentOfficeAddressState: {
        error: "",
        label: "",
      },
      agentOfficeAddressZipCode: {
        error: "",
        label: "",
      },
      annualReportNotification: {
        checkboxText: "",
      },
      businessName: {
        alertAvailable: "",
        alertDesignator: "",
        alertRestrictedWord: "",
        alertSpecialCharacters: "",
        alertUnavailable: "",
        confirmBusinessNameError: "",
        confirmBusinessNameLabel: "",
        description: "",
        errorInlineEmpty: "",
        errorInlineNeedsToSearch: "",
        errorInlineUnavailable: "",
        header: "",
        label: "",
        overrides: {
          foreign: {
            description: "",
            header: "",
          },
        },
      },
      businessPurpose: {
        addButtonText: "",
        body: "",
        label: "",
      },
      businessStartDate: {
        error30Days: "",
        error90Days: "",
        errorFuture: "",
        errorToday: "",
        label: "",
        labelContextualInfo: "",
        labelSecondaryText: "",
      },
      businessSuffix: {
        error: "",
        label: "",
        labelContextualInfo: "",
        labelSecondaryTextForeignCorporation: "",
        optionsUpdatedSnackbarAlert: "",
      },
      businessTotalStock: {
        error: "",
        label: "",
      },
      canCreateLimitedPartner: {
        body: "",
        label: "",
        reviewStepNo: "",
        reviewStepYes: "",
      },
      canGetDistribution: {
        body: "",
        label: "",
        reviewStepNo: "",
        reviewStepYes: "",
      },
      canMakeDistribution: {
        body: "",
        label: "",
        reviewStepNo: "",
        reviewStepYes: "",
      },
      certificateOfStanding: {
        cost: "",
        label: "",
        labelContextualInfo: "",
        overrides: {
          "c-corporation": {
            cost: "",
          },
          "foreign-nonprofit": {
            cost: "",
          },
          "limited-partnership": {
            cost: "",
          },
          nonprofit: {
            cost: "",
          },
          "s-corporation": {
            cost: "",
          },
        },
      },
      certifiedCopyOfFormationDocument: {
        cost: "",
        label: "",
        labelContextualInfo: "",
      },
      combinedInvestment: {
        body: "",
        label: "",
      },
      contactFirstName: {
        error: "",
        label: "",
      },
      contactLastName: {
        error: "",
        label: "",
      },
      contactPhoneNumber: {
        error: "",
        label: "",
        labelSecondaryText: "",
      },
      corpWatchNotification: {
        checkboxText: "",
      },
      createLimitedPartnerTerms: {
        label: "",
      },
      directors: {
        addButtonText: "",
        description: "",
        error: "",
        label: "",
        modalSaveButton: "",
        modalTitle: "",
        placeholder: "",
        reviewStepHeader: "",
        subheader: "",
        successSnackbarBody: "",
        successSnackbarHeader: "",
      },
      dissolution: {
        body: "",
        label: "",
      },
      foreignDateOfFormation: {
        error: "",
        label: "",
        labelSecondaryText: "",
      },
      foreignGoodStandingFile: {
        contextualLabel: "",
        errorMessageFileSize: "",
        errorMessageFileType: "",
        errorMessageRequired: "",
        helperText: "",
        label: "",
      },
      foreignStateOfFormation: {
        error: "",
        label: "",
      },
      getDistributionTerms: {
        label: "",
      },
      hasNonprofitBoardMembers: {
        body: "",
        label: "",
        noReviewText: "",
        reviewLabel: "",
        yesReviewText: "",
      },
      incorporators: {
        addButtonText: "",
        description: "",
        error: "",
        label: "",
        modalTitle: "",
        overrides: {
          "limited-partnership": {
            description: "",
          },
        },
        placeholder: "",
        successSnackbarBody: "",
        successSnackbarHeader: "",
      },
      isVeteranNonprofit: {
        description: "",
        error: "",
        label: "",
        reviewTextNo: "",
        reviewTextYes: "",
      },
      makeDistributionTerms: {
        label: "",
      },
      members: {
        addButtonText: "",
        addressCheckboxText: "",
        description: "",
        error: "",
        expandText: "",
        label: "",
        modalSaveButton: "",
        modalTitle: "",
        placeholder: "",
        subheader: "",
        successSnackbarBody: "",
        successSnackbarHeader: "",
      },
      nonprofitAssetDistributionSpecified: {
        body: "",
        label: "",
      },
      nonprofitAssetDistributionTerms: {
        label: "",
      },
      nonprofitBoardMemberQualificationsSpecified: {
        body: "",
        label: "",
      },
      nonprofitBoardMemberQualificationsTerms: {
        label: "",
      },
      nonprofitBoardMemberRightsSpecified: {
        body: "",
        label: "",
      },
      nonprofitBoardMemberRightsTerms: {
        label: "",
      },
      nonprofitTrusteesMethodSpecified: {
        body: "",
        label: "",
      },
      nonprofitTrusteesMethodTerms: {
        label: "",
      },
      officialFormationDocument: {
        cost: "",
        label: "",
        labelContextualInfo: "",
        overrides: {
          nonprofit: {
            cost: "",
          },
        },
      },
      paymentType: {
        achLabel: "",
        costColumnLabel: "",
        costSubtotalLabel: "",
        costTotalLabel: "",
        costTotalPaymentDisclaimer: "",
        creditCardLabel: "",
        error: "",
        label: "",
        paymentCosts: {
          ach: "",
          creditCardExtra: "",
          creditCardInitial: "",
        },
        reviewStepServicesHeader: "",
        reviewStepsServicesSelected: "",
        serviceColumnLabel: "",
      },
      signers: {
        addButtonText: "",
        aidText: "",
        columnLabel: "",
        deleteLabel: "",
        description: "",
        editLabel: "",
        errorBannerCheckbox: "",
        errorBannerMinimum: "",
        errorBannerSignerName: "",
        errorBannerSignerTitle: "",
        errorInlineAdditionalSignerName: "",
        errorInlineNameAndSignature: "",
        errorInlineSignature: "",
        errorInlineSignerName: "",
        errorInlineSignerTitle: "",
        keepInMindCallout: "",
        label: "",
        nameLabel: "",
        overrides: {
          "foreign-limited-liability-company": {
            description: "",
          },
          "limited-liability-partnership": {
            description: "",
          },
        },
        placeholder: "",
        tableHeaderActions: "",
        tableHeaderAddress: "",
        tableHeaderName: "",
        tableHeaderSign: "",
        titleLabel: "",
      },
      trustees: {
        addButtonText: "",
        description: "",
        error: "",
        label: "",
        modalSaveButton: "",
        modalTitle: "",
        placeholder: "",
        subheader: "",
        successSnackbarBody: "",
        successSnackbarHeader: "",
        trusteeFullName: "",
      },
      willPracticeLaw: {
        error: "",
        label: "",
        radioNoText: "",
        radioYesText: "",
        subtitle: "",
      },
      withdrawals: {
        body: "",
        label: "",
      },
    },
    general: {
      ariaContextStepperLabels: "",
      ariaContextStepperStateComplete: "",
      ariaContextStepperStateError: "",
      ariaContextStepperStateIncomplete: "",
      ariaContextWillLooseCalendarAndCertificationAccess: "",
      ariaContextWillNeedToProvideBusinessDate: "",
      backButtonText: "",
      charactersLabel: "",
      editButtonText: "",
      genericErrorText: "",
      helpButtonText: "",
      initialNextButtonText: "",
      initialNextNexusButtonText: "",
      maximumLengthErrorText: "",
      nextButtonText: "",
      notEntered: "",
      optionalLabel: "",
      paymentDisclaimer: "",
      previousButtonText: "",
      radioNoText: "",
      radioYesText: "",
      removeSectionText: "",
      submitButtonText: "",
      viewLessButtonText: "",
      viewMoreButtonText: "",
    },
    interimSuccessPage: {
      alertText: "",
      bodyText: "",
      buttonText: "",
      modalBody: "",
      modalCancel: "",
      modalContinue: "",
      modalTitle: "",
    },
    intro: {
      certificateOfGoodStandingAlert: {
        beginning: "",
        end: "",
      },
      default: "",
      foreign: "",
    },
    legalStructure: {
      contextualInfo: "",
      domesticLabels: {
        "c-corporation": "",
        "limited-liability-company": "",
        "limited-liability-partnership": "",
        "limited-partnership": "",
        nonprofit: "",
        "s-corporation": "",
      },
      foreignLabels: {
        "c-corporation": "",
        "limited-liability-company": "",
        "limited-liability-partnership": "",
        "limited-partnership": "",
        nonprofit: "",
        "s-corporation": "",
      },
      label: "",
      warningModalBody: "",
      warningModalCancelButton: "",
      warningModalContinueButton: "",
      warningModalHeader: "",
    },
    nonprofitProvisions: {
      description: "",
      label: "",
      radioInBylawsText: "",
      radioInFormText: "",
    },
    partnershipRights: {
      description: "",
      label: "",
      radioNoText: "",
      radioYesText: "",
      reviewStepTermsLabel: "",
    },
    registeredAgent: {
      agentNumberLabel: "",
      agentNumberLabelSecondary: "",
      checkboxCheckedScreenReaderAnnouncement: "",
      checkboxUnCheckedScreenReaderAnnouncement: "",
      infoCalloutBullets: [],
      infoCalloutFooter: "",
      infoCalloutHeading: "",
      infoCalloutIntro: "",
      label: "",
      manualEntryCheckboxLabel: "",
      noteBody: "",
      noteTitle: "",
      radioButtonAuthorizedRepText: "",
      radioButtonManualText: "",
      radioButtonMyselfText: "",
      radioButtonNumberText: "",
      radioButtonProfessionalServiceText: "",
      sameAddressCheckbox: "",
      sectionDescription: "",
      whoToListSubheading: "",
    },
    sections: {
      addressAddButtonText: "",
      addressHeader: "",
      businessNameAndStructureHeader: "",
      contactInfoHeader: "",
      notificationsDescription: "",
      notificationsHeader: "",
      review: {
        billingContactHeader: "",
        confirmationBox: {
          confirmationError: "",
          correctionFeesCheckbox: "",
          namesAddressesDatesCheckbox: "",
          permanentRecordCheckbox: "",
          title: "",
        },
        nameLabel: "",
        warningAlert: "",
      },
      servicesDescription: "",
      servicesHeader: "",
    },
    successPage: {
      amendmentText: "",
      body: "",
      certifiedDocLabel: "",
      confirmationNumberLabel: "",
      entityIdLabel: "",
      formationDocLabel: "",
      header: "",
      standingDocLabel: "",
      subheader: "",
      surveyLinkText: "",
    },
  },
  formationDateDeletionModal: {
    areYouSureModalBody: "",
    cancelButtonText: "",
    deleteButtonText: "",
    description: "",
    header: "",
  },
  formationDateModal: {
    areYouSureModalBody: "",
    areYouSureModalCancelButtonText: "",
    areYouSureModalContinueButtonText: "",
    areYouSureModalHeader: "",
    cancelButtonText: "",
    dateOfFormationErrorText: "",
    description: "",
    fieldDescription: "",
    fieldLabel: "",
    header: "",
    lockedStatusTooltipText: "",
    saveButtonText: "",
  },
  fundingDefaults: {
    issuingAgencyText: "",
  },
  fundingsOnboardingModal: {
    headerTooltip: "",
    incompleteWarningMultipleText: "",
    incompleteWarningSingularText: "",
    modalHeader: "",
    nonProfitQuestion: {
      questionText: "",
      responses: {
        no: "",
        yes: "",
      },
      selectAnAnswerText: "",
    },
    numberOfEmployeesQuestion: {
      questionText: "",
      selectAnAnswerText: "",
    },
    page: {
      noResultsFoundAlertText: "",
    },
    pageHeader: {
      buttonText: "",
      headerText: "",
      logoAriaText: "",
      logoLink: "",
      subHeaderText: "",
    },
    saveButtonText: "",
  },
  governmentContracting: {
    backButtonLabel: "",
    continueButtonLabel: "",
    stepFourButtonLink: "",
    stepFourButtonText: "",
    stepFourContent: "",
    stepFourStepperLabel: "",
    stepOneButtonLink: "",
    stepOneButtonText: "",
    stepOneContent: "",
    stepOneStepperLabel: "",
    stepThreeButtonLink: "",
    stepThreeButtonText: "",
    stepThreeContent: "",
    stepThreeStepperLabel: "",
    stepTwoButtonLink: "",
    stepTwoButtonText: "",
    stepTwoContent: "",
    stepTwoStepperLabel: "",
  },
  headerDefaults: {
    defaultHeaderText: "",
    genericStarterKitText: "",
    noUserNameHeaderText: "",
    starterKitText: "",
  },
  housingRegistrationSearchTask: {
    address1Label: "",
    address2Label: "",
    applicationsFoundHeader: "",
    errorTextFieldsRequired: "",
    errorTextNoHotelMotelRegistrations: "",
    errorTextNoMultipleDwellingRegistrations: "",
    errorTextNoPropertyInterestFound: "",
    errorTextSearchFailed: "",
    informationalIncomplete: "",
    informationalInReview: "",
    informationalRejected: "",
    informationalReturned: "",
    municipalityLabel: "",
    registrationBuildingCountText: "",
    registrationCallToActionPrimaryText: "",
    registrationCallToActionSecondaryText: "",
    registrationFoundIncompleteReturnedText: "",
    registrationFoundInReviewText: "",
    registrationInReviewMessage: "",
    registrationRejectedOrReturnedMessage: "",
    registrationSearchPrompt: "",
    registrationStartDateText: "",
    registrationStatusText: "",
    registrationTab1Text: "",
    registrationTab2Text: "",
    renewRegistrationMessage: "",
    reviewApplicationCallToActionLink: "",
    reviewMyApplicationCallToAction: "",
    stateLabel: "",
    submitText: "",
  },
  landingPage: {
    card1Button: "",
    card1ButtonLink: "",
    card1Header: "",
    card1SupportingText: "",
    card2Button: "",
    card2ButtonLink: "",
    card2Header: "",
    card2SupportingText: "",
    card3Button: "",
    card3Header: "",
    card3SupportingText: "",
    heroCallOutFirstLineText: "",
    heroSupportingText: "",
    landingPageFundingTile: "",
    landingPageGetStartedTileLine1: "",
    landingPageGetStartedTileLine2: "",
    landingPageOutOfStateTile: "",
    landingPageRegisterBizTile: "",
    landingPageRunBizTile: "",
    landingPageStartBizTile: "",
    landingPageTaxesTile: "",
    section2CallToActionText: "",
    section2HeaderText: "",
    section2SupportingText: "",
    section3CallToActionText: "",
    section3HeaderText: "",
    section3SupportingText: "",
    section4FirstIconText: "",
    section4HeaderText: "",
    section4SecondIconText: "",
    section4ThirdIconText: "",
    section5FirstHeaderText: "",
    section5FirstSupportingText: "",
    section5SecondHeaderText: "",
    section5SecondSupportingText: "",
    section5ThirdHeaderText: "",
    section5ThirdSupportingText: "",
    section6Header: "",
    tileTitleText: "",
  },
  landingPageExperienceB: {
    heroCallOutFirstLineText: "",
    heroSupportingText: "",
    section2CallToActionText: "",
    section2HeaderText: "",
    section2SupportingText: "",
    section3CallToActionText: "",
    section4SecondIconText: "",
    section5FirstHeaderText: "",
    section5FirstSupportingText: "",
    section5ThirdSupportingText: "",
  },
  legalMessageDefaults: {
    legalMessageLegalChat: "",
    legalMessageTextOne: "",
    legalMessageTextTwo: "",
  },
  licenseSearchTask: {
    abandonedStatusText: "",
    activePermitStatusText: "",
    address1Label: "",
    address2Label: "",
    applicationChecklistItemsText: "",
    approvedStatusText: "",
    barredPermitStatusText: "",
    businessNameLabel: "",
    checklistCompletedStatusText: "",
    checkStatusText: "",
    closedPermitStatusText: "",
    completedStatusText: "",
    deficienciesSubmittedStatusText: "",
    deletedPermitStatusText: "",
    deniedPermitStatusText: "",
    draftStatusText: "",
    editButtonText: "",
    errorTextFieldsRequired: "",
    errorTextNotFound: "",
    errorTextSearchFailed: "",
    expiredPermitStatusText: "",
    foundText: "",
    inactiveStatusText: "",
    incompleteStatusText: "",
    issuingAgencyNameText: "",
    notApplicableStatusText: "",
    outOfBusinessPermitStatusText: "",
    pendingDeficienciesStatusText: "",
    pendingPermitStatusText: "",
    pendingReinstatementStatusText: "",
    pendingRenewalStatusText: "",
    permitStatusText: "",
    primaryCTAFirstLineText: "",
    primaryCTASecondLineText: "",
    reinstatementPendingPermitStatusText: "",
    revokedStatusText: "",
    scheduledStatusText: "",
    secondaryCTAFirstLineText: "",
    secondaryCTASecondLineText: "",
    specialReviewStatusText: "",
    stateLabel: "",
    submittedStatusText: "",
    submitText: "",
    suspendedStatusText: "",
    tab1Text: "",
    tab2Text: "",
    tooltipText: "",
    underInternalReviewStatusText: "",
    voluntarySurrenderPermitStatusText: "",
    withdrawnPermitStatusText: "",
    zipCodeLabel: "",
  },
  loginSupportPage: {
    forMoreAssistance: "",
    havingTrouble: "",
    lastUpdated: "",
    logoutAndTryAgain: "",
    logoutAndTryAgainUnlinked: "",
    logoutButtonText: "",
    logoutIfStillHavingTrouble: "",
    multipleAccountsCallout: "",
    myNewJerseyIntroContent: "",
    pageTitle: "",
    steps: [],
    supportCallout: {
      body: "",
      buttonText: "",
      header: "",
    },
    unlinkedAccount: "",
  },
  manageBusinessVehicles: {
    h2HeaderText: "",
    inputErrorText: "",
    learnMoreText: "",
    noResponseText: "",
    pageLevelAlertText: "",
    radioOptionOneText: "",
    radioOptionTwoText: "",
    radioQuestionText: "",
    resultsScreenHeaderText: "",
    saveButtonText: "",
    successAlertButtonText: "",
    successAlertText: "",
    tooltipText: "",
    yesResponseText: "",
  },
  navigationDefaults: {
    addBusinessButton: "",
    backToProfileLinkText: "",
    getStartedText: "",
    landingPageDropDownTitle: "",
    logInButton: "",
    logoutButton: "",
    myNJAccountText: "",
    navBarBusinessNJGovAltText: "",
    navBarBusinessNJGovAriaLabel: "",
    navBarBusinessNJGovLink: "",
    navBarGuestAccountText: "",
    navBarGuestBusinessText: "",
    navBarGuestRegistrationText: "",
    navBarMyAccountText: "",
    navBarUnnamedBusinessText: "",
    navBarUnnamedDbaBusinessText: "",
    navBarUnnamedForeignRemoteSellerWorkerText: "",
    navBarUnnamedOwnedBusinessText: "",
    profileLinkText: "",
    removeBusinessLinkText: "",
  },
  navigationQuickLinks: {
    navBarGrowLink: "",
    navBarGrowText: "",
    navBarMobileQuickLinksTitle: "",
    navBarOperateLink: "",
    navBarOperateText: "",
    navBarPlanLink: "",
    navBarPlanText: "",
    navBarSearchLink: "",
    navBarSearchText: "",
    navBarStartLink: "",
    navBarStartText: "",
    navBarUpdatesLink: "",
    navBarUpdatesText: "",
  },
  nexusNameSearch: {
    availableText: "",
    dbaAvailableText: "",
    dbaNameDescription: "",
    dbaNameHeader: "",
    dbaNameSearchLabel: "",
    dbaNameSearchSubmitButton: "",
    dbaUnavailableText: "",
    nexusNextButton: "",
    searchAgainButtonText: "",
    unavailableText: "",
  },
  onboardingDefaults: {
    additionalBusinessFinalNextButtonText: "",
    backButtonText: "",
    errorTextMinimumNumericField: "",
    errorTextMinimumRangeNumericField: "",
    finalNextButtonText: "",
    nextButtonText: "",
    pageTitle: "",
    returnToPreviousBusiness: "",
    stepXTemplate: "",
  },
  pageNotFoundError: {
    errorChatWithExpert: "",
    errorDescriptionPt1: "",
    errorDescriptionPt2: "",
    errorHeader: "",
  },
  pagesMetadata: {
    dashboardTitle: "",
    deadLinksTitle: "",
    deadUrlsTitle: "",
    featureFlagsTitle: "",
    homeTitle: "",
    notesMd: "",
    profileTitle: "",
    siteDescription: "",
    titlePostfix: "",
  },
  passengerTransportCdlTabOne: {
    bodyText: "",
    disabledTooltipText: "",
    firstQuestionAlertFieldNameText: "",
    firstQuestionFalseText: "",
    firstQuestionInputErrorText: "",
    firstQuestionLabel: "",
    firstQuestionTrueText: "",
    headerText: "",
    pageLevelAlertText: "",
    saveButton: "",
    secondQuestionAlertFieldNameText: "",
    secondQuestionFalseText: "",
    secondQuestionInputErrorText: "",
    secondQuestionLabel: "",
    secondQuestionTrueText: "",
  },
  passengerTransportCdlTabTwo: {
    bodyText: "",
    classBWithoutSInfoAccordionText: "",
    classBWithoutSReqAccordionText: "",
    classBWithoutSResAccordionText: "",
    classBWithoutSText: "",
    classBWithSInfoAccordionText: "",
    classBWithSReqAccordionText: "",
    classBWithSResAccordionText: "",
    classBWithSText: "",
    classCWithoutSInfoAccordionText: "",
    classCWithoutSReqAccordionText: "",
    classCWithoutSResAccordionText: "",
    classCWithoutSText: "",
    classCWithSInfoAccordionText: "",
    classCWithSReqAccordionText: "",
    classCWithSResAccordionText: "",
    classCWithSText: "",
    contactAccordionHeaderText: "",
    contactAccordionText: "",
    eligibilityAccordionHeaderText: "",
    eligibilityAccordionText: "",
    headerText: "",
    infoAccordionHeaderWithoutSText: "",
    infoAccordionHeaderWithSText: "",
    issuingAgencyLabelText: "",
    issuingAgencyText: "",
    requirementsAccordionHeaderText: "",
    responseAccordionHeaderText: "",
    successAlertButtonText: "",
    successAlertText: "",
  },
  profileDefaults: {
    default: {
      annualReportDeadlineHeader: "",
      annualReportDeadlineSubText: "",
      backButtonText: "",
      cannabisLocationAlert: "",
      certificationDocFileTitle: "",
      contactAndNotificationsSubText: "",
      contactInformationHeading: "",
      contactInformationSubText: "",
      errorAlertMultipleFields: "",
      errorDefaultTextBody: "",
      errorErrorAlertOneField: "",
      errorTextBody: "",
      errorTextEmail: "",
      errorTextHeader: "",
      escapeModalBody: "",
      escapeModalEscape: "",
      escapeModalHeader: "",
      escapeModalQuestion: "",
      escapeModalReturn: "",
      escapeModalSaveChanges: "",
      essentialQuestionAlertText: "",
      filterCertificationsAndFundingHeader: "",
      filterCertificationsAndFundingSubText: "",
      formationDocFileTitle: "",
      locationBasedRequirementsHeader: "",
      locationBasedRequirementsSubText: "",
      lockedFieldTooltipText: "",
      notificationIncompleteTasksDescription: "",
      notificationIncompleteTasksLabel: "",
      notificationNewsletterDescription: "",
      notificationNewsletterLabel: "",
      notificationProductNewsDescription: "",
      notificationProductNewsLabel: "",
      permitsAndLicensesSubText: "",
      profileAddressNotProvided: "",
      profilePageTitlePrefix: "",
      profileTabContactTitle: "",
      profileTabDocsTitle: "",
      profileTabInfoTitle: "",
      profileTabNoteTitle: "",
      profileTabNumbersTitle: "",
      profileTabPermitsTitle: "",
      profileTabPersonalizeYourTasksTitle: "",
      profileTabSlugs: {
        contact: "",
        documents: "",
        info: "",
        notes: "",
        numbers: "",
        permits: "",
        personalize: "",
      },
      saveButtonText: "",
      secondaryNavigationAriaLabel: "",
      securityMattersHeading: "",
      securityMattersText: "",
      standingDocFileTitle: "",
      successTextBody: "",
      successTextHeader: "",
      typesOfNotificationsHeading: "",
      typesOfNotificationsSubText: "",
      yourProfileHelpsWithRecommendationsCallout: "",
    },
    fields: {
      businessAddress: {
        default: {
          header: "",
          intlAddress: "",
          usAddress: "",
        },
      },
      businessName: {
        default: {
          description: "",
          header: "",
          headerContextualInfo: "",
        },
      },
      businessPersona: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          radioButtonForeignText: "",
          radioButtonOwningText: "",
          radioButtonStartingText: "",
        },
      },
      cannabisLicenseType: {
        default: {
          description: "",
          header: "",
          radioButtonAnnualText: "",
          radioButtonConditionalText: "",
        },
      },
      carService: {
        default: {
          description: "",
          header: "",
          radioButtonBothText: "",
          radioButtonHighCapacityText: "",
          radioButtonStandardText: "",
        },
      },
      certifiedInteriorDesigner: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      constructionType: {
        default: {
          description: "",
          header: "",
          radioButtonBothText: "",
          radioButtonCommercialOrIndustrialText: "",
          radioButtonResidentialText: "",
        },
      },
      dateOfFormation: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
          headerNotBolded: "",
        },
      },
      deptOfLaborEin: {
        default: {
          hideButtonText: "",
          showButtonText: "",
        },
      },
      documents: {
        default: {
          header: "",
          placeholder: "",
        },
      },
      elevatorOwningBusiness: {
        default: {
          altDescription: "",
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      employerId: {
        default: {
          description: "",
          header: "",
          headerContextualInfo: "",
          headerNotBolded: "",
        },
      },
      employmentAgency: {
        default: {
          description: "",
          header: "",
        },
      },
      employmentPersonnelServiceType: {
        default: {
          description: "",
          header: "",
          radioButtonEmployersText: "",
          radioButtonJobSeekersText: "",
        },
      },
      employmentPlacementType: {
        default: {
          description: "",
          header: "",
          radioButtonBothText: "",
          radioButtonPermanentText: "",
          radioButtonTemporaryText: "",
        },
      },
      entityId: {
        default: {
          description: "",
          header: "",
          headerContextualInfo: "",
        },
      },
      existingEmployees: {
        default: {
          description: "",
          header: "",
        },
        overrides: {
          OWNING: {
            description: "",
            header: "",
          },
        },
      },
      foreignBusinessTypeIds: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          NEXUS: "",
          optionContent: {
            companyOperatedVehiclesInNJ: "",
            employeeOrContractorInNJ: "",
            employeesInNJ: "",
            none: "",
            officeInNJ: "",
            propertyInNJ: "",
            revenueInNJ: "",
            transactionsInNJ: "",
          },
          REMOTE_SELLER: "",
          REMOTE_WORKER: "",
        },
      },
      hasThreeOrMoreRentalUnits: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      homeBasedBusiness: {
        default: {
          altDescription: "",
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      homeContractor: {
        default: {
          description: "",
          header: "",
        },
      },
      industryId: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
          searchAffirmation: "",
        },
        onboarding: {
          default: {
            description: "",
          },
        },
      },
      interstateLogistics: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      interstateMoving: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      isChildcareForSixOrMore: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      legalStructureId: {
        default: {
          addText: "",
          description: "",
          editText: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
          notEnteredText: "",
          optionContent: {
            "c-corporation": "",
            "general-partnership": "",
            "limited-liability-company": "",
            "limited-liability-partnership": "",
            "limited-partnership": "",
            nonprofit: "",
            "s-corporation": "",
            "sole-proprietorship": "",
          },
        },
      },
      liquorLicense: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      municipality: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
        },
        overrides: {
          FOREIGN: {
            description: "",
          },
          OWNING: {
            description: "",
          },
        },
      },
      naicsCode: {
        default: {
          addText: "",
          altDescription: "",
          editText: "",
          header: "",
          headerContextualInfo: "",
          notEnteredText: "",
        },
      },
      nexusBusinessName: {
        default: {
          addButton: "",
          editButton: "",
          emptyBusinessPlaceHolder: "",
          outOfStateNameHeader: "",
        },
      },
      nexusDbaName: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
        },
      },
      nonEssentialQuestions: {
        default: {
          linkToPermitsHeader: "",
          linkToPermitsTextAfterButton: "",
          linkToPermitsTextBeforeButton: "",
          linkToPermitsTextButton: "",
          optionalText: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
          sectionHeader: "",
          sectionSubText: "",
        },
      },
      notes: {
        default: {
          description: "",
          header: "",
        },
      },
      ownershipTypeIds: {
        default: {
          description: "",
          header: "",
          headerNotBolded: "",
        },
        overrides: {
          OWNING: {
            header: "",
            headerNotBolded: "",
          },
        },
      },
      petCareHousing: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      plannedRenovationQuestion: {
        default: {
          altDescription: "",
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      propertyLeaseType: {
        default: {
          description: "",
          header: "",
          radioButtonBothText: "",
          radioButtonLongTermRentalText: "",
          radioButtonShortTermRentalText: "",
        },
      },
      providesStaffingService: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      publicWorksContractor: {
        default: {
          description: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      raffleBingoGames: {
        default: {
          altDescription: "",
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      realEstateAppraisalManagement: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      requiresCpa: {
        default: {
          description: "",
          header: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
      residentialConstructionType: {
        default: {
          description: "",
          header: "",
          radioButtonBothText: "",
          radioButtonHomeRenovationsText: "",
          radioButtonNewHomeConstructionText: "",
        },
      },
      responsibleOwnerName: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
        },
      },
      sectorId: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
        },
        onboarding: {
          default: {
            description: "",
          },
          overrides: {
            OWNING: {
              description: "",
            },
          },
        },
      },
      taxId: {
        default: {
          description: "",
          disclaimerMd: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
        },
      },
      taxPin: {
        default: {
          description: "",
          errorTextRequired: "",
          header: "",
          headerContextualInfo: "",
          hideButtonText: "",
          hideButtonTextMobile: "",
          showButtonText: "",
          showButtonTextMobile: "",
        },
      },
      tradeName: {
        default: {
          errorTextRequired: "",
          header: "",
        },
      },
      willSellPetCareItems: {
        default: {
          description: "",
          radioButtonFalseText: "",
          radioButtonTrueText: "",
        },
      },
    },
  },
  registeredForTaxesModal: {
    areYouSureTaxBody: "",
    areYouSureTaxCancelButton: "",
    areYouSureTaxContinueButton: "",
    areYouSureTaxTitle: "",
  },
  removeBusinessModal: {
    agreementCheckboxErrorText: "",
    agreementCheckboxText: "",
    businessRemovalText: "",
    cancelButtonText: "",
    filingOfficialBusinessClosureText: "",
    header: "",
    irreversibleOperationText: "",
    removeBusinessButtonText: "",
  },
  searchBusinessNameTask: {
    availableText: "",
    designatorText: "",
    errorTextBadInput: "",
    errorTextSearchFailed: "",
    nameHasBeenUpdatedText: "",
    searchButtonText: "",
    similarUnavailableNamesText: "",
    unavailableText: "",
    updateButtonText: "",
  },
  sectionHeaders: {
    DOMESTIC_EMPLOYER_SECTION: "",
    PLAN: "",
    START: "",
  },
  selfRegistration: {
    accountSuccessSnackbarBody: "",
    accountSuccessSnackbarTitle: "",
    accountSuccessSnackbarTitleExistingAccount: "",
    closeButtonText: "",
    confirmEmailFieldLabel: "",
    continueWithoutSaving: "",
    emailFieldLabel: "",
    errorTextDuplicateSignUp: "",
    errorTextEmailsNotMatching: "",
    errorTextFullName: "",
    errorTextFullNameLength: "",
    errorTextFullNameSpecialCharacter: "",
    errorTextFullNameStartWithLetter: "",
    errorTextGeneric: "",
    errorTextPhoneNumber: "",
    errorTextRequiredFields: "",
    investNewarkContactSharingCheckboxLabel: "",
    nameFieldLabel: "",
    needsAccountModalBody: "",
    needsAccountModalButtonText: "",
    needsAccountModalSubText: "",
    needsAccountModalTitle: "",
    newsletterCheckboxLabel: "",
    phoneNumberFieldLabel: "",
    phoneNumberFieldLabelOptional: "",
    signUpTitleText: "",
    submitButtonText: "",
    updatesAndRemindersCheckboxLabel: "",
    userTestingCheckboxLabel: "",
  },
  siteWideErrorMessages: {
    errorRadioButton: "",
    errorScreenReaderInlinePrefix: "",
    errorTextCachedOnly: "",
    errorTextNoData: "",
    errorTextUpdateFailed: "",
  },
  skipToMainContent: {
    buttonText: "",
  },
  starterKits: {
    hero: {
      ctaButton: "",
      subtitle: "",
      title: "",
    },
    seo: {
      description: "",
      imageAltText: "",
    },
    solutions: {
      card1: {
        body: "",
        title: "",
      },
      card2: {
        body: "",
        title: "",
      },
      card3: {
        body: "",
        title: "",
      },
      ctaButton: "",
      subtitle: "",
      title: "",
    },
    steps: {
      ctaButton: "",
      title: "",
    },
  },
  taskDefaults: {
    backButtonText: "",
    backToRoadmapText: "",
    continueButtonText: "",
    defaultCallToActionText: "",
    editText: "",
    formNameText: "",
    issuingAgencyText: "",
    loadingTaskDependencies: "",
    markAsCompleteButtonText: "",
    nextTaskButtonText: "",
    pageTitle: "",
    previousTaskButtonText: "",
    removeText: "",
    requiredLabelText: "",
    secondaryNavigationAriaLabel: "",
    taskProgressSnackbarHeading: "",
    taskProgressSnackbarPrefix: "",
    unlockedByPlural: "",
    unlockedBySingular: "",
  },
  taskProgress: {
    COMPLETED: "",
    TO_DO: "",
  },
  taskProgressCard: {
    optionalTasksPlural: "",
    optionalTasksSingular: "",
    requiredTasksPlural: "",
    requiredTasksSingular: "",
  },
  taxAccess: {
    businessFieldErrorName: "",
    businessFieldHeader: "",
    businessFieldMarkdown: "",
    businessOwnerDescription: "",
    businessOwnerName: "",
    failedBusinessFieldHelper: "",
    failedErrorMessageHeader: "",
    failedResponsibleOwnerFieldHelper: "",
    failedTaxIdHelper: "",
    failedUnknownMarkdown: "",
    legalStructureDropDownHeader: "",
    responsibleOwnerFieldErrorName: "",
    stepOneErrorBanner: "",
    stepOneHeader: "",
    stepOneNextButton: "",
    stepTwoBackButton: "",
    stepTwoCancelButton: "",
    stepTwoErrorBanner: "",
    stepTwoHeader: "",
    stepTwoNextButton: "",
    taxAccessHeader: "",
    taxCalendarAccessBody: "",
    taxFieldErrorName: "",
    taxIdHeader: "",
    taxIdMarkdown: "",
  },
  taxCalendar: {
    accessBody: "",
    accessButton: "",
    pendingCopyMarkdown: "",
    registrationFollowUpCopyMarkdown: "",
    snackbarSuccessBody: "",
    snackbarSuccessHeader: "",
  },
  taxClearanceCertificateDownload: {
    buttonText: "",
    calloutText: "",
    headerTwoLabel: "",
  },
  taxClearanceCertificateShared: {
    backButtonText: "",
    businessNameErrorText: "",
    liveChatButtonText: "",
    liveChatLabelText: "",
    pluralErrorText: "",
    requestingAgencyErrorText: "",
    saveButtonText: "",
    singularErrorText: "",
    stepperOneLabel: "",
    stepperThreeLabel: "",
    stepperTwoLabel: "",
  },
  taxClearanceCertificateStep1: {
    content: "",
    continueButtonText: "",
    issuingAgencyLabelText: "",
    issuingAgencyText: "",
  },
  taxClearanceCertificateStep2: {
    businessInformationSectionHeader: "",
    requestingAgencyLabel: "",
    requestingAgencySectionHeader: "",
  },
  taxClearanceCertificateStep3: {
    addressLabel: "",
    businessNameLabel: "",
    certificationReasonLabel: "",
    editButtonText: "",
    errorTextIneligible: "",
    errorTextMissingField: "",
    errorTextPreviouslyReceivedCertificate: "",
    errorTextStatusVerification: "",
    errorTextSystem: "",
    errorTextValidation: "",
    firstSectionHeader: "",
    mainTitleHeader: "",
    secondSectionHeader: "",
    stateTaxIdLabel: "",
    taxPinLabel: "",
  },
  taxId: {
    descriptionText: "",
    hideButtonText: "",
    hideButtonTextMobile: "",
    lockedPostText: "",
    lockedPreText: "",
    saveButtonText: "",
    showButtonText: "",
    showButtonTextMobile: "",
  },
  unsupportedNavigatorUserPage: {
    subtitle: "",
    title: "",
  },
  xrayRegistrationTask: {
    accordionHeader: "",
    activeDescription: "",
    activeStatusStatusText: "",
    address1Label: "",
    address2Label: "",
    addressZipCodeLabel: "",
    annualFee: "",
    ariaLabel: "",
    businessNameLabel: "",
    callToActionPrimaryText: "",
    callToActionSecondaryText: "",
    checkStatusText: "",
    editButtonText: "",
    equipmentText: "",
    errorTextFieldsRequired: "",
    errorTextNotFound: "",
    errorTextSearchFailed: "",
    expiredDescription: "",
    expiredDescriptionCallToAction: "",
    expiredStatusStatusText: "",
    expiredText: "",
    expiresInLessThanAMonthText: "",
    futureExpirationDateText: "",
    inactiveDescription: "",
    inactiveDescriptionCallToAction: "",
    inactiveStatusText: "",
    issuingAgency: "",
    issuingAgencyText: "",
    lastUpdatedText: "",
    manufacturer: "",
    modelNumber: "",
    noInformationAvailable: "",
    registrationCategory: "",
    registrationNumber: "",
    registrationStatusText: "",
    renewRegistrationLink: "",
    roomId: "",
    serialNumber: "",
    stateLabel: "",
    submitText: "",
    tab1Text: "",
    tab2Text: "",
  },
  xrayRenewal: {
    ariaLabel: "",
    callToActionPrimaryText: "",
    callToActionSecondaryText: "",
    tab1Text: "",
    tab2Text: "",
  },
});
