"use client";

/**
 * Renders the client-side Pagefind search experience.
 */

import type { ChangeEvent, FormEvent } from "react";
import { Fragment, useEffect, useState } from "react";

import type { SearchPageContent } from "@/domain/landing/types";

/**
 * URL for the generated Pagefind ESM bundle.
 */
const PAGEFIND_SCRIPT_PATH = "/pagefind/pagefind.js";

/**
 * Maximum section-level matches shown below each page result.
 */
const MAX_SUB_RESULTS_PER_RESULT = 3;

/**
 * Describes options accepted by the generated Pagefind search function.
 */
export interface PagefindSearchOptions {
  /** Optional Pagefind filter map. */
  readonly filters?: Record<string, string | readonly string[]>;
  /** Optional Pagefind sort map. */
  readonly sort?: Record<string, "asc" | "desc">;
}

/**
 * Data returned by a loaded Pagefind result.
 */
export interface PagefindResultData {
  /** Public URL for the search result. */
  readonly url: string;
  /** Highlighted HTML excerpt generated by Pagefind. */
  readonly excerpt: string;
  /** Plain-text excerpt generated by Pagefind. */
  readonly plain_excerpt: string;
  /** Metadata values attached to the result. */
  readonly meta: Readonly<Record<string, string>>;
  /** Optional section-level results generated from page headings. */
  readonly sub_results?: readonly PagefindSubResult[];
}

/**
 * One section-level Pagefind result.
 */
export interface PagefindSubResult {
  /** Public URL for the section result. */
  readonly url: string;
  /** Section heading used as the result title. */
  readonly title: string;
  /** Highlighted HTML excerpt generated by Pagefind. */
  readonly excerpt: string;
  /** Plain-text excerpt generated by Pagefind. */
  readonly plain_excerpt: string;
}

/**
 * One Pagefind result before its fragment data is loaded.
 */
export interface PagefindResult {
  /** Stable Pagefind result identifier. */
  readonly id: string;
  /** Pagefind relevance score. */
  readonly score: number;
  /** Word positions matched by the query. */
  readonly words: readonly number[];
  /** Loads the result fragment data. */
  readonly data: () => Promise<PagefindResultData>;
}

/**
 * Response returned by the generated Pagefind search function.
 */
export interface PagefindSearchResponse {
  /** Result entries ordered by Pagefind relevance. */
  readonly results: readonly PagefindResult[];
  /** Number of results before filters are applied. */
  readonly unfilteredResultCount: number;
}

/**
 * Generated Pagefind module surface used by this component.
 */
export interface PagefindModule {
  /** Runs a Pagefind search for the supplied term. */
  readonly search: (
    term: string,
    options?: PagefindSearchOptions,
  ) => Promise<PagefindSearchResponse>;
}

/**
 * Loads the generated Pagefind module.
 */
export type PagefindModuleLoader = () => Promise<PagefindModule>;

/**
 * Describes props accepted by the search results component.
 */
export interface SearchResultsProps {
  /** Localized labels and state text for the search page. */
  readonly content: SearchPageContent;
  /** Query parsed from the page URL on the server. */
  readonly initialQuery: string;
  /** Optional Pagefind loader override for component tests. */
  readonly pagefindModuleLoader?: PagefindModuleLoader;
}

/**
 * One Pagefind result with loaded fragment data.
 */
interface LoadedPagefindResult {
  /** Stable Pagefind result identifier. */
  readonly id: string;
  /** Pagefind relevance score. */
  readonly score: number;
  /** Loaded result fragment data. */
  readonly data: PagefindResultData;
}

/**
 * Search state before a query has been submitted.
 */
interface IdleSearchState {
  /** State discriminator. */
  readonly kind: "idle";
}

/**
 * Search state while Pagefind is loading or querying.
 */
interface LoadingSearchState {
  /** State discriminator. */
  readonly kind: "loading";
  /** Submitted query being searched. */
  readonly query: string;
}

/**
 * Search state for a completed query with matches.
 */
interface SuccessSearchState {
  /** State discriminator. */
  readonly kind: "success";
  /** Submitted query used for the current results. */
  readonly query: string;
  /** Loaded results returned by Pagefind. */
  readonly results: readonly LoadedPagefindResult[];
  /** Result count reported by Pagefind before filters. */
  readonly resultCount: number;
}

/**
 * Search state for a completed query without matches.
 */
interface NoResultsSearchState {
  /** State discriminator. */
  readonly kind: "no-results";
  /** Submitted query that returned no matches. */
  readonly query: string;
}

/**
 * Search state for a failed Pagefind load or query.
 */
interface ErrorSearchState {
  /** State discriminator. */
  readonly kind: "error";
  /** Original error value caught at the Pagefind boundary. */
  readonly error: unknown;
}

/**
 * State variants used by the search results component.
 */
type SearchState =
  | IdleSearchState
  | LoadingSearchState
  | SuccessSearchState
  | NoResultsSearchState
  | ErrorSearchState;

/**
 * Describes input for loading one Pagefind result fragment.
 */
interface LoadPagefindResultParams {
  /** Pagefind result whose fragment should be loaded. */
  readonly result: PagefindResult;
}

/**
 * Describes input for loading Pagefind result fragments.
 */
interface LoadPagefindResultsParams {
  /** Pagefind results whose fragments should be loaded. */
  readonly results: readonly PagefindResult[];
}

/**
 * Describes input for executing a Pagefind search.
 */
interface ExecuteSearchParams {
  /** Submitted query to run. */
  readonly query: string;
  /** Loader for the generated Pagefind module. */
  readonly pagefindModuleLoader: PagefindModuleLoader;
  /** Receives the next component state when the query settles. */
  readonly setSearchState: (state: SearchState) => void;
  /** Indicates whether this effect is still current. */
  readonly isCurrent: () => boolean;
}

/**
 * Describes input for building a result summary.
 */
interface BuildResultSummaryParams {
  /** Localized search page content. */
  readonly content: SearchPageContent;
  /** Number of results returned for the query. */
  readonly resultCount: number;
  /** Submitted query used for the current results. */
  readonly query: string;
}

/**
 * Describes input for updating the browser URL.
 */
interface UpdateBrowserSearchQueryParams {
  /** Submitted query to write to the `q` search parameter. */
  readonly query: string;
}

/**
 * Describes one safe excerpt segment parsed from Pagefind highlight markup.
 */
interface HighlightSegment {
  /** Text content rendered by React with normal escaping. */
  readonly text: string;
  /** Indicates the segment was wrapped in Pagefind mark tags. */
  readonly isHighlighted: boolean;
}

/**
 * Describes input for rendering one excerpt segment.
 */
interface RenderHighlightSegmentParams {
  /** Parsed excerpt segment. */
  readonly segment: HighlightSegment;
  /** Zero-based segment position used for React keys. */
  readonly index: number;
}

/**
 * Singleton promise for the generated Pagefind module.
 */
let pagefindModulePromise: Promise<PagefindModule> | undefined;

/**
 * Dynamically imports the generated Pagefind module.
 */
const importPagefindModule = async (): Promise<PagefindModule> => {
  const pagefindScriptPath: string = PAGEFIND_SCRIPT_PATH;
  const pagefindModule = (await import(
    /* webpackIgnore: true */ pagefindScriptPath
  )) as PagefindModule;

  return pagefindModule;
};

/**
 * Loads the generated Pagefind module once per browser session.
 *
 * @returns Pagefind module with the search API.
 * @example
 * ```ts
 * const pagefind = await loadPagefindModule();
 * ```
 */
export const loadPagefindModule: PagefindModuleLoader = async () => {
  pagefindModulePromise ??= importPagefindModule();

  return pagefindModulePromise;
};

/**
 * Loads one Pagefind result fragment.
 */
const loadPagefindResult = async ({
  result,
}: LoadPagefindResultParams): Promise<LoadedPagefindResult> => {
  const data = await result.data();

  return {
    id: result.id,
    score: result.score,
    data,
  };
};

/**
 * Loads all Pagefind result fragments concurrently.
 */
const loadPagefindResults = async ({
  results,
}: LoadPagefindResultsParams): Promise<readonly LoadedPagefindResult[]> => {
  const resultPromises = results.map((result) => {
    return loadPagefindResult({ result });
  });

  return Promise.all(resultPromises);
};

/**
 * Executes one Pagefind search and updates component state.
 */
const executeSearch = async ({
  query,
  pagefindModuleLoader,
  setSearchState,
  isCurrent,
}: ExecuteSearchParams): Promise<void> => {
  setSearchState({ kind: "loading", query });

  try {
    const pagefindModule = await pagefindModuleLoader();
    const response = await pagefindModule.search(query);
    const loadedResults = await loadPagefindResults({ results: response.results });

    if (!isCurrent()) {
      return;
    }

    if (loadedResults.length === 0) {
      setSearchState({ kind: "no-results", query });
      return;
    }

    setSearchState({
      kind: "success",
      query,
      results: loadedResults,
      resultCount: response.unfilteredResultCount,
    });
  } catch (error) {
    if (isCurrent()) {
      setSearchState({ kind: "error", error });
    }
  }
};

/**
 * Builds localized result count text.
 */
const buildResultSummary = ({ content, resultCount, query }: BuildResultSummaryParams): string => {
  const resultLabel = resultCount === 1 ? content.resultSingularLabel : content.resultPluralLabel;

  return `${resultCount} ${resultLabel} ${content.resultQueryConnector} "${query}"`;
};

/**
 * Updates the current browser URL with the submitted query.
 */
const updateBrowserSearchQuery = ({ query }: UpdateBrowserSearchQueryParams): void => {
  const nextUrl = new URL(window.location.href);

  if (hasSubmittedQuery(query)) {
    nextUrl.searchParams.set("q", query);
  } else {
    nextUrl.searchParams.delete("q");
  }

  window.history.pushState(null, "", nextUrl.toString());
};

/**
 * Checks whether a query has non-empty submitted text.
 */
const hasSubmittedQuery = (query: string): boolean => {
  return query.trim().length > 0;
};

/** Opening mark tag emitted by Pagefind excerpts. */
const PAGEFIND_MARK_OPEN_TAG = "<mark>";

/** Closing mark tag emitted by Pagefind excerpts. */
const PAGEFIND_MARK_CLOSE_TAG = "</mark>";

/** Token pattern for Pagefind highlight tags. */
const PAGEFIND_MARK_TAG_PATTERN = /(<mark>|<\/mark>)/g;

/**
 * Parses Pagefind highlight markup into React-renderable text segments.
 */
const buildHighlightSegments = (html: string): readonly HighlightSegment[] => {
  const tokens = html.split(PAGEFIND_MARK_TAG_PATTERN);
  const segments: HighlightSegment[] = [];
  let isHighlighted = false;

  for (const token of tokens) {
    if (token === PAGEFIND_MARK_OPEN_TAG) {
      isHighlighted = true;
    } else if (token === PAGEFIND_MARK_CLOSE_TAG) {
      isHighlighted = false;
    } else if (token.length > 0) {
      segments.push({ text: token, isHighlighted });
    }
  }

  return segments;
};

/**
 * Renders one parsed Pagefind excerpt segment.
 */
const renderHighlightSegment = ({ segment, index }: RenderHighlightSegmentParams) => {
  const key = `highlight-segment-${index}`;

  if (segment.isHighlighted) {
    return <mark key={key}>{segment.text}</mark>;
  }

  return <Fragment key={key}>{segment.text}</Fragment>;
};

/**
 * Renders one Pagefind excerpt.
 */
const renderExcerpt = (html: string) => {
  const segments = buildHighlightSegments(html);

  return (
    <p className="margin-top-1 margin-bottom-0">
      {segments.map((segment, index) => {
        return renderHighlightSegment({ segment, index });
      })}
    </p>
  );
};

/**
 * Renders one section-level Pagefind result.
 */
const renderSubResult = (subResult: PagefindSubResult) => {
  return (
    <li className="margin-top-2" key={subResult.url}>
      <a className="usa-link" href={subResult.url}>
        {subResult.title}
      </a>
      {renderExcerpt(subResult.excerpt)}
    </li>
  );
};

/**
 * Renders a bounded list of section-level Pagefind results.
 */
const renderSubResults = (subResults: readonly PagefindSubResult[] | undefined) => {
  if (!subResults || subResults.length === 0) {
    return null;
  }

  return (
    <ul className="usa-list margin-top-2">
      {subResults.slice(0, MAX_SUB_RESULTS_PER_RESULT).map(renderSubResult)}
    </ul>
  );
};

/**
 * Renders one loaded Pagefind result.
 */
const renderLoadedResult = (result: LoadedPagefindResult) => {
  const title = result.data.meta.title ?? result.data.url;

  return (
    <li className="search-result" key={result.id}>
      <h2 className="font-heading-md margin-bottom-1">
        <a className="usa-link" href={result.data.url}>
          {title}
        </a>
      </h2>
      {renderExcerpt(result.data.excerpt)}
      {renderSubResults(result.data.sub_results)}
    </li>
  );
};

/**
 * Renders the state-specific search result area.
 */
const renderSearchState = (content: SearchPageContent, state: SearchState) => {
  if (state.kind === "idle") {
    return (
      <section className="usa-prose margin-top-4" aria-live="polite">
        <h2>{content.emptyStateTitle}</h2>
        <p>{content.emptyStateDescription}</p>
      </section>
    );
  }

  if (state.kind === "loading") {
    return (
      <p className="margin-top-4" aria-live="polite">
        {content.loadingLabel}
      </p>
    );
  }

  if (state.kind === "no-results") {
    return (
      <section className="usa-prose margin-top-4" aria-live="polite">
        <h2>{content.noResultsTitle}</h2>
        <p>{content.noResultsDescription}</p>
      </section>
    );
  }

  if (state.kind === "error") {
    return (
      <section className="usa-alert usa-alert--error margin-top-4" aria-live="polite">
        <div className="usa-alert__body">
          <h2 className="usa-alert__heading">{content.errorTitle}</h2>
          <p className="usa-alert__text">{content.errorDescription}</p>
        </div>
      </section>
    );
  }

  return (
    <section className="margin-top-4" aria-live="polite">
      <p className="text-bold">
        {buildResultSummary({
          content,
          resultCount: state.resultCount,
          query: state.query,
        })}
      </p>
      <ol className="usa-list search-results-list">{state.results.map(renderLoadedResult)}</ol>
    </section>
  );
};

/**
 * Renders the client-side search form and result states.
 *
 * @param props Component props.
 * @param props.content Localized labels and state text.
 * @param props.initialQuery Query parsed from the page URL.
 * @param props.pagefindModuleLoader Optional loader override for tests.
 * @returns Search form and current results.
 * @example
 * ```tsx
 * <SearchResults content={messages.search} initialQuery="business" />
 * ```
 */
export const SearchResults = ({
  content,
  initialQuery,
  pagefindModuleLoader = loadPagefindModule,
}: SearchResultsProps) => {
  const [query, setQuery] = useState(initialQuery);
  const [submittedQuery, setSubmittedQuery] = useState(initialQuery);
  const [searchState, setSearchState] = useState<SearchState>(
    hasSubmittedQuery(initialQuery) ? { kind: "loading", query: initialQuery } : { kind: "idle" },
  );

  useEffect(() => {
    const normalizedQuery = submittedQuery.trim();

    if (!hasSubmittedQuery(normalizedQuery)) {
      setSearchState({ kind: "idle" });
      return;
    }

    let current = true;
    const isCurrent = (): boolean => {
      return current;
    };

    void executeSearch({
      query: normalizedQuery,
      pagefindModuleLoader,
      setSearchState,
      isCurrent,
    });

    return () => {
      current = false;
    };
  }, [submittedQuery, pagefindModuleLoader]);

  const handleQueryInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    setQuery(event.target.value);
  };

  const handleSearchSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const normalizedQuery = query.trim();

    updateBrowserSearchQuery({ query: normalizedQuery });
    setSubmittedQuery(normalizedQuery);
  };

  return (
    <>
      <form className="usa-search usa-search--big margin-top-4" onSubmit={handleSearchSubmit}>
        <label className="usa-sr-only" htmlFor="search-page-query">
          {content.inputLabel}
        </label>
        <input
          className="usa-input"
          id="search-page-query"
          name="q"
          onChange={handleQueryInputChange}
          type="search"
          value={query}
        />
        <button className="usa-button" type="submit">
          {content.submitLabel}
        </button>
      </form>
      {renderSearchState(content, searchState)}
    </>
  );
};
