export const cmsCollections = [
  {
    label: "🟥 BUSINESS FORMATION",
    children: ["Biz Form - Config", "Biz Form - DBA Tasks", "Nexus"],
  },
  {
    label: "🌲 ENVIRONMENTAL COMPLIANCE",
    children: ["Env Comp - Config"],
  },
  {
    label: "🟧 CERTIFICATION OPPS",
    children: ["Cert Opps - Content", "Cert Opps - Archive"],
  },
  {
    label: "🟨 FUNDING OPPS",
    children: ["Fund Opps - Content", "Fund Opps - Archived"],
  },
  {
    label: "🟩 ROADMAPS",
    children: [
      "Roadmaps - Industries",
      "Roadmaps - Add-ons",
      "Roadmaps - Non Essential Questions",
      "Roadmaps - Settings",
    ],
  },
  {
    label: "🟦 TASKS",
    children: [
      "Tasks - Config",
      "Tasks - All",
      "License Tasks (Navigator with Webflow mappings)",
      "Raffle Bingo Steps",
      "Webflow Licenses",
      "Tasks - Cannabis License",
      "Tasks - Cannabis Priority Status",
      "Tasks - Cigarette License",
      "Tasks - EIN",
      "Tasks - Tax ID",
      "Tasks - Municipal",
      "Tasks - NAICS Code",
      "Tasks - Business Structure",
      "Xray",
    ],
  },
  {
    label: "📅 CALENDAR",
    children: [
      "Tax Access Modal Config",
      "Consumer Affairs License Expiration / Renewal Events",
      "Taxes Filings - All",
      "Xray Renewal Calendar Event",
    ],
  },
  {
    label: "🟥 DASHBOARD",
    children: ["Dashboard - Config", "Sidebar Cards Content"],
  },
  {
    label: "🟧 ANYTIME ACTIONS",
    children: [
      "Anytime Action Categories",
      "Anytime Action Tasks",
      "Anytime Action With Consumer Affairs License Integrations (Reinstatements)",
      "Tax Clearance Anytime Action",
    ],
  },
  {
    label: "🟨 PAGE METADATA",
    children: ["Page Metadata"],
  },
  {
    label: "🟦 MISC",
    children: [
      "Anytime Action Reinstatement and License Calendar Event Status Defaults",
      "Starter Kits",
      "Callout Defaults",
      "Dropdown Mappings",
      "General Config",
      "Landing Pages",
      "License Search Task",
      "Profile Page",
      "Fundings Onboarding Page",
      "Contextual Information",
      "404 Page",
      "Check Account Email Page",
      "Component Accessibility",
      "Global Error Messages",
      "Navigation Config",
      "Filing Defaults",
      "Skip to main content",
      "Beta Bar",
      "Tax Calendar Defaults",
      "Formation Task - Date of Formation Modal",
      "Tax Task - Tax Registration Modal",
      "Funding Defaults",
      "Legal Messages",
      "Onboarding Defaults",
      "Page Footer",
      "Section Headers",
      "Self Registration",
      "Shared Header Defaults",
      "Task Defaults",
      "Task - Business Name Search",
      "Task Progress",
      "Task Progress Card",
      "Navigator Unsupported User Page",
      "Autosave",
      "Formation Date Deletion Modal",
    ],
  },
  {
    label: "ℹ️ SUPPORT",
    children: ["Login Support Page"],
  },
];
