name: "Deploy Setup"
description: "Runs configure-and-build, sets up Docker Buildx and triggers CDK deployment."

inputs:
  stage:
    description: "Stage to deploy to."
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure and Build
      uses: ./.github/actions/configure-and-build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Fetch Cognito Metadata
      shell: bash
      run: |
        aws s3 cp \
          s3://nj-bfs-all-accounts-config-files/${{ inputs.stage }}-cognito-metadata.xml \
          ${{ github.workspace }}/cognito-metadata.xml

    - name: Debug metadata env path
      shell: bash
      run: |
        echo "COGNITO_METADATA_FILE=$COGNITO_METADATA_FILE"

    - name: Deploy CDK
      uses: ./.github/actions/deploy-cdk
      env:
        COGNITO_METADATA_FILE: ${{ github.workspace }}/cognito-metadata.xml
