import { filterByOwnerType } from "@client/dep/filterByOwnerType";

describe("filterByOwnerType", () => {
  it("filters out entries that are not of type OWNER", () => {
    const entries = [
      {
        registrationNumber: "330061",
        roomId: "01",
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "46-404600G",
        serialNumber: "770-1676141DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "OWNER",
        disposalDate: undefined,
        businessName: "SOME BUSINESS LLC",
      },
      {
        registrationNumber: "330061",
        roomId: "01",
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "46-404600G",
        serialNumber: "770-1676141DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "OWNER",
        disposalDate: undefined,
        businessName: "SOME BUSINESS LLC",
      },
      {
        registrationNumber: "330062",
        roomId: undefined,
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "110-0150G1",
        serialNumber: "62-1664624DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "STAFF",
        disposalDate: "07/31/2019",
        businessName: "SOME BUSINESS LLC",
      },
      {
        registrationNumber: "330062",
        roomId: undefined,
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "110-0150G1",
        serialNumber: "62-1664624DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "STAFF",
        disposalDate: "07/31/2019",
        businessName: "SOME BUSINESS LLC",
      },
    ];

    expect(filterByOwnerType(entries)).toEqual([
      {
        registrationNumber: "330061",
        roomId: "01",
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "46-404600G",
        serialNumber: "770-1676141DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "OWNER",
        disposalDate: undefined,
        businessName: "SOME BUSINESS LLC",
      },
      {
        registrationNumber: "330061",
        roomId: "01",
        registrationCategory: "DENTIST",
        name: "GENDEX CORP.",
        manufacturer: "DENTIST",
        modelNumber: "46-404600G",
        serialNumber: "770-1676141DP",
        annualFee: 92,
        expirationDate: "08/31/2025",
        deactivationDate: undefined,
        streetAddress: "123 Main Street",
        city: "PARAMUS",
        state: "NJ",
        zipCode: "12345",
        status: "Active",
        contactType: "OWNER",
        disposalDate: undefined,
        businessName: "SOME BUSINESS LLC",
      },
    ]);
  });
});
