/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BusinessForm {
  user?: {
    firstName?: string;
    lastName?: string;
    email?: string;
    [k: string]: unknown | undefined;
  };
  businessType?: {
    businessType?: "Restaurant" | "Other";
    [k: string]: unknown | undefined;
  };
  businessName?: {
    businessName?: string;
    [k: string]: unknown | undefined;
  };
  businessDescription?: {
    businessDescription?: string;
    [k: string]: unknown | undefined;
  };
  businessStructure?: {
    businessStructure?: "LLC" | "LP" | "S-Corp";
    [k: string]: unknown | undefined;
  };
  locations?: {
    locations?: [
      {
        zipCode?: string;
        license?: boolean;
        [k: string]: unknown | undefined;
      },
      ...{
        zipCode?: string;
        license?: boolean;
        [k: string]: unknown | undefined;
      }[]
    ];
    [k: string]: unknown | undefined;
  };
  [k: string]: unknown | undefined;
}
