backend:
  name: github
  repo: newjersey/navigator.business.nj.gov
  branch: content-repo
  base_url: https://522jjs5e28.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /dev/api/cms/auth
  use_graphql: true
  squash_merges: true
  commit_messages:
    create: "chore: creating {{collection}} {{slug}}"
    update: "chore: updating {{collection}} {{slug}}"
publish_mode: editorial_workflow
local_backend: true
media_folder: web/public/img
logo_url: https://dev.navigator.business.nj.gov/img/Navigator-logo.svg
public_folder: web/public
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
