export const LandingPageDefaults: Record<string, string> = {
  heroCalloutFirstLineText: "Your Business,",
  heroCalloutSecondLineText: "Your Way",
  heroSupportingText: "Get your free, personalized checklist to start your new business in New Jersey.",
  herocallToActionText: "Get started",
  section2HeaderFirstLineText: "Starting a business in New",
  section2HeaderSecondLineText: " Jersey has never been ",
  section2HeaderThirdLineText: "faster or easier!",
  section2SupportingText:
    "Learn what forms and licenses you need to start your business and avoid fines. We’ll ask you a few onboarding questions; be prepared to tell us your:",
  section2Icon1Text: "Legal Structure",
  section2Icon2Text: "Industry",
  section2Icon3Text: "Location",
  section3HeaderFirstLineText: "Not Starting a",
  section3HeaderSecondLineText: " New Business?",
  column1Header: "Explore Business.NJ.gov",
  column1SupportingText: "Visit our website with more resources to start, operate, and grow your business.",
  column1Button: "Visit the Site",
  column1ButtonLink: "https://business.nj.gov/",
  column1Image: "../img/Not-Starting-1-visit-site.svg",
  column1ImageAlt: "Visit Business.NJ.gov site icon",
  column2Header: "Sign Up for Our Newsletter",
  column2SupportingText:
    "Already a registered business and want to know the lastest grants and regulations likely to affect your business? Join our weekly newsletter.",
  column2Button: "Sign Up",
  column2ButtonLink: "https://business.nj.gov/newsletter-signup",
  column2Image: "../img/Not-Starting-2-newsletter.svg",
  column2ImageAlt: "Sign up for our newsletter icon",
  column3Header: "Chat with a New Jersey Representative",
  column3SupportingText:
    "Local experts are available 9 a.m–5 p.m Eastern Time, Monday through Friday, to help you with any business challenge.",
  column3Button: "Start chatting",
  column3ButtonLink: "",
  column3Image: "../img/Not-Starting-3-chat.svg",
  column3ImageAlt: "Chat with a New Jersey representative icon",
};
