name: "Package WebApp Docker Image"
description: "Builds and pushes the WebApp Docker image to ECR with multiple tags."

inputs:
  image-name:
    description: "Base name for the Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Web Docker Image
      shell: bash
      run: scripts/build-webapp-docker-image.sh "${{ inputs.image-name }}"
    - name: Smoke Test Web Docker Image
      shell: bash
      run: scripts/smoke-test-webapp-docker-image.sh "${{ inputs.image-name }}"
    - name: Push Web Docker Image
      shell: bash
      run: scripts/push-webapp-docker-image.sh "${{ inputs.image-name }}"
