name: "Deploy Storybook"
description: "Builds Storybook, uploads it to S3, and configures the S3 website."

inputs:
  storybook_s3_bucket:
    description: "S3 bucket name for Storybook"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Storybook
      shell: bash
      run: |
        yarn workspace @businessnjgovnavigator/web build-storybook -o .storybook/build

    - name: Upload Storybook to S3
      shell: bash
      run: |
        aws s3 sync web/.storybook/build s3://${{ inputs.storybook_s3_bucket }} --delete

    - name: Configure Storybook S3 Website
      shell: bash
      run: |
        aws s3 website s3://${{ inputs.storybook_s3_bucket }} \
          --index-document index.html \
          --error-document index.html
