export const BusinessFormationDefaults: Record<string, string> = {
  notSetBusinessNameText: "Not set",
  initialNextButtonText: "Start Forming My Business",
  nextButtonText: "Continue",
  previousButtonText: "Back",
  submitButtonText: "Submit",
  suffixErrorText: "Business suffix is required",
  businessNameLabel: "Business Name:",
  legalStructureLabel: "Legal Structure:",
  updateYourProfileDisplayText: "${value}, if this is incorrect, ${link}.",
  updateYourProfileLinkText: "update your profile",
  startDateErrorText: "The business formation date must be today or a future date formatted as MM/DD/YYYY",
  businessAddressLine1ErrorText: "Address is required",
  businessAddressCityLabel: "City",
  notSetBusinessAddressCityLabel: "Not set",
  businessAddressZipCodeErrorText: "Must be a NJ Zip Code between 07001 and 08999",
  agentNumberErrorText: "Registered Agent Number must be 4-7 digits",
  agentNameErrorText: "Agent name is required",
  agentEmailErrorText: "Agent email is required",
  agentOfficeAddressLine1ErrorText: "Agent office address is required",
  agentOfficeAddressCityErrorText: "Agent office city is required",
  agentOfficeAddressZipCodeErrorText: "Must be a NJ Zip Code between 07001 and 08999",
  signerErrorText: "First signer is required",
  addNewSignerButtonText: "Add New Signer",
  creditCardPaymentTypeLabel: "Credit Card",
  achPaymentTypeLabel: "E-Check",
  paymentTypeErrorText: "Payment type is required",
  documentTableColumn2Label: "Documentation Options",
  documentTableColumn3Label: "New Jersey Statutory Fee",
  documentTableTotalCostLabel: "Total:",
  submitErrorHeading: "Formation failed. Errors found in the following fields:",
  contactFirstNameErrorText: "First name is required",
  contactLastNameErrorText: "Last name is required",
  contactPhoneNumberErrorText: "Phone number is required",
  missingFieldsOnSubmitModalText: "Cannot submit. The following fields are missing or invalid:",
  successPageHeader: "Hooray!",
  successPageSubheader: "You have successfully formed your business entity and reserved your business name!",
  successPageBody:
    "Below are your requested documents, you can download them for your records until ${expirationDate}.",
  formationDocLabel: "Official Formation Document (PDF)",
  standingDocLabel: "Certificate of Good Standing (PDF)",
  certifiedDocLabel: "Certified Copy of Formation (PDF)",
  entityIdLabel: "Entity ID",
  confirmationNumberLabel: "Confirmation Number:",
  alreadySubmittedHeader: "Successfully Submitted",
  alreadySubmittedText:
    "You've already successfully submitted your business formation. " +
    "If you finished paying and got your documents, you're all set. " +
    "If you still need to complete payment, ${link}.",
  alreadySubmittedLinkText: "visit your specialized payment page",
  membersNewButtonText: "Add New Member",
  membersExpandText: "Expand",
  membersTableColumn: "Name,Street,Actions",
  membersModalNextButtonText: "Add Member",
  membersModalBackButtonText: "Cancel",
  membersSuccessTextHeader: "Member Added",
  membersSuccessTextBody: "A member has been added successfully",
  NameErrorText: "Name is required",
  AddressErrorText: "Address is required",
  AddressCityErrorText: "City is required",
  AddressStateErrorText: "state is required",
  AddressZipCodeErrorText: "Must be a valid 5 digit Zip Code",
};
