export type StateObject = {
  shortCode: string;
  name: string;
};
export const arrayOfStateObjects: StateObject[] = [
  { shortCode: "AK", name: "Alaska" },
  { shortCode: "AL", name: "Alabama" },
  { shortCode: "AR", name: "Arkansas" },
  { shortCode: "AS", name: "American Samoa" },
  { shortCode: "AZ", name: "Arizona" },
  { shortCode: "CA", name: "California" },
  { shortCode: "CO", name: "Colorado" },
  { shortCode: "CT", name: "Connecticut" },
  { shortCode: "DC", name: "District of Columbia" },
  { shortCode: "DE", name: "Delaware" },
  { shortCode: "FL", name: "Florida" },
  { shortCode: "GA", name: "Georgia" },
  { shortCode: "GU", name: "Guam" },
  { shortCode: "HI", name: "Hawaii" },
  { shortCode: "IA", name: "Iowa" },
  { shortCode: "ID", name: "Idaho" },
  { shortCode: "IL", name: "Illinois" },
  { shortCode: "IN", name: "Indiana" },
  { shortCode: "KS", name: "Kansas" },
  { shortCode: "KY", name: "Kentucky" },
  { shortCode: "LA", name: "Louisiana" },
  { shortCode: "MA", name: "Massachusetts" },
  { shortCode: "MD", name: "Maryland" },
  { shortCode: "ME", name: "Maine" },
  { shortCode: "MI", name: "Michigan" },
  { shortCode: "MN", name: "Minnesota" },
  { shortCode: "MO", name: "Missouri" },
  { shortCode: "MS", name: "Mississippi" },
  { shortCode: "MT", name: "Montana" },
  { shortCode: "NC", name: "North Carolina" },
  { shortCode: "ND", name: "North Dakota" },
  { shortCode: "NE", name: "Nebraska" },
  { shortCode: "NH", name: "New Hampshire" },
  { shortCode: "NJ", name: "New Jersey" },
  { shortCode: "NM", name: "New Mexico" },
  { shortCode: "NV", name: "Nevada" },
  { shortCode: "NY", name: "New York" },
  { shortCode: "OH", name: "Ohio" },
  { shortCode: "OK", name: "Oklahoma" },
  { shortCode: "OR", name: "Oregon" },
  { shortCode: "PA", name: "Pennsylvania" },
  { shortCode: "PR", name: "Puerto Rico" },
  { shortCode: "RI", name: "Rhode Island" },
  { shortCode: "SC", name: "South Carolina" },
  { shortCode: "SD", name: "South Dakota" },
  { shortCode: "TN", name: "Tennessee" },
  { shortCode: "TX", name: "Texas" },
  { shortCode: "UT", name: "Utah" },
  { shortCode: "VA", name: "Virginia" },
  { shortCode: "VI", name: "Virgin Islands" },
  { shortCode: "VT", name: "Vermont" },
  { shortCode: "WA", name: "Washington" },
  { shortCode: "WI", name: "Wisconsin" },
  { shortCode: "WV", name: "West Virginia" },
  { shortCode: "WY", name: "Wyoming" },
];
