name: Auto Deploy Staging on Push to Staging

on:
  push:
    branches:
      - "staging-*"

jobs:
  deploy-staging:
    uses: newjersey/navigator.business.nj.gov/.github/workflows/deploy-staging.yml@convertDeployJobsToGHA
    secrets: inherit
